<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>ActiveDev.Data.SqlClient</RootNamespace>
    <MyType>Windows</MyType>
    <OptionStrict>On</OptionStrict>
    <AssemblyOriginatorKeyFile>ActiveDev.pfx</AssemblyOriginatorKeyFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>AdSqlSupportComponents.xml</DocumentationFile>
    <NoWarn>42353,42354,42355</NoWarn>
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineDebug>false</DefineDebug>
    <DocumentationFile>AdSqlSupportComponents.xml</DocumentationFile>
    <NoWarn>42353,42354,42355</NoWarn>
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
    <DocumentationFile>AdSqlSupportComponents.xml</DocumentationFile>
    <NoWarn>42353,42354,42355</NoWarn>
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
    <DocumentationFile>AdSqlSupportComponents.xml</DocumentationFile>
    <NoWarn>42353,42354,42355</NoWarn>
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
    <DocumentationFile>AdSqlSupportComponents.xml</DocumentationFile>
    <NoWarn>42353,42354,42355</NoWarn>
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
    <DocumentationFile>AdSqlSupportComponents.xml</DocumentationFile>
    <NoWarn>42353,42354,42355</NoWarn>
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="AdAttachDatabaseDialog.Designer.vb">
      <DependentUpon>AdAttachDatabaseDialog.vb</DependentUpon>
    </Compile>
    <Compile Update="AdDatabaseConnectionDialog.Designer.vb">
      <DependentUpon>AdDatabaseConnectionDialog.vb</DependentUpon>
    </Compile>
    <Compile Update="AdSqlDatabaseConnector.Designer.vb">
      <DependentUpon>AdSqlDatabaseConnector.vb</DependentUpon>
    </Compile>
    <Compile Update="AdSqlDatabaseConnector.vb">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="AdSqlDatabasesInfoComboBox.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="AdSQLDirectoryPicker.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="AdSqlDirectoryPickerDialog.Designer.vb">
      <DependentUpon>AdSqlDirectoryPickerDialog.vb</DependentUpon>
    </Compile>
    <Compile Update="AdSqlInfoComboBase.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="AdSqlInstanceInfoComboBox.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="AdSqlInstanceConnectionDialog.Designer.vb">
      <DependentUpon>AdSqlInstanceConnectionDialog.vb</DependentUpon>
    </Compile>
    <Compile Update="AdSqlServerConnector.Designer.vb">
      <DependentUpon>AdSqlServerConnector.vb</DependentUpon>
    </Compile>
    <Compile Update="AdSqlServerConnector.vb">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="AdTSqlScriptProcessorDialog.Designer.vb">
      <DependentUpon>AdTSqlScriptProcessorDialog.vb</DependentUpon>
    </Compile>
    <Compile Update="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="ActiveDev.pfx" />
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{94E38DFF-614B-4CBD-B67C-F211BB35CE8B}" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="4.6.0" />
  </ItemGroup>
</Project>
