<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<OutputType>Exe</OutputType>
		<LangVersion>Preview</LangVersion>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<RootNamespace>WinForms.Analyzers.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.2" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.12.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
		<PackageReference Include="xunit.v3" Version="3.2.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WinForms.Analyzers\WinForms.Analyzers.csproj" />
	</ItemGroup>

</Project>
