<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Facesso</RootNamespace>
    <StartupObject>Facesso.Program</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="System.Data.Entity" />
    <Reference Include="System.Windows" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="FacessoShellRelated\frmFacessoShell.Designer.cs">
      <DependentUpon>frmFacessoShell.cs</DependentUpon>
    </Compile>
    <Compile Update="frmDateShiftPicker.designer.cs">
      <DependentUpon>frmDateShiftPicker.cs</DependentUpon>
    </Compile>
    <Compile Update="frmError.designer.cs">
      <DependentUpon>frmError.cs</DependentUpon>
    </Compile>
    <Compile Update="frmSplash.designer.cs">
      <DependentUpon>frmSplash.cs</DependentUpon>
    </Compile>
    <Compile Update="frmHiddenTestAndAdmin.designer.cs">
      <DependentUpon>frmHiddenTestAndAdmin.cs</DependentUpon>
    </Compile>
    <Compile Update="frmTSImportsBeta.designer.cs">
      <DependentUpon>frmTSImportsBeta.cs</DependentUpon>
    </Compile>
    <Compile Update="frmInfo.designer.cs">
      <DependentUpon>frmInfo.cs</DependentUpon>
    </Compile>
    <Compile Update="ToolStripMonthCalender.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="FacessoShellRelated\frmFacessoShell.resx">
      <DependentUpon>frmFacessoShell.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="frmDateShiftPicker.resx">
      <DependentUpon>frmDateShiftPicker.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="frmError.resx">
      <DependentUpon>frmError.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="frmSplash.resx">
      <DependentUpon>frmSplash.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="frmHiddenTestAndAdmin.resx">
      <DependentUpon>frmHiddenTestAndAdmin.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="frmTSImportsBeta.resx">
      <DependentUpon>frmTSImportsBeta.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="frmInfo.resx">
      <DependentUpon>frmInfo.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ActiveDevelop.SqlTools\ActiveDevelop.SqlTools.csproj" />
    <ProjectReference Include="..\ADDataTypes\ADDataTypes.csproj" />
    <ProjectReference Include="..\ADInfoItem\ADInfoItem.csproj" />
    <ProjectReference Include="..\ADLicenceManager\ADLicenceManager.csproj" />
    <ProjectReference Include="..\ADSqlSupportComponents\ADSqlSupportComponents.csproj" />
    <ProjectReference Include="..\ADSundries\ADSundries.csproj" />
    <ProjectReference Include="..\Controls\ADNullableValueControls.csproj" />
    <ProjectReference Include="..\Facesso.Data\Facesso.Data.csproj" />
    <ProjectReference Include="..\Facesso.Functions\Facesso.Functions.csproj" />
    <ProjectReference Include="..\Facesso.GenericControls\Facesso.GenericControls.csproj" />
    <ProjectReference Include="..\Facesso.Interfaces\Facesso.Interfaces.csproj" />
    <ProjectReference Include="..\Facesso.EntityModel\Facesso.EntityModel.csproj" />
    <ProjectReference Include="..\Facesso.Generic\Facesso.Generic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MvvmForms" Version="2.1.7-Beta3" />
    <PackageReference Include="MvvmFormsBase" Version="2.1.6-Beta" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="System.Reactive.Core" Version="6.1.0" />
    <PackageReference Include="System.Reactive.Interfaces" Version="6.1.0" />
    <PackageReference Include="System.Reactive.Linq" Version="6.1.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
    <PackageReference Include="System.Resources.Extensions" Version="4.6.0" />
  </ItemGroup>

</Project>
