'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Facesso")>  _
Partial Public Class FacessoDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertTimeLog(instance As TimeLog)
    End Sub
  Partial Private Sub UpdateTimeLog(instance As TimeLog)
    End Sub
  Partial Private Sub DeleteTimeLog(instance As TimeLog)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.Facesso.Interfaces.My.MySettings.Default.FacessoConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property TimeLog() As System.Data.Linq.Table(Of TimeLog)
		Get
			Return Me.GetTable(Of TimeLog)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.TimeLog_AddItemsForAddEdit")>  _
	Public Function TimeLog_AddItemsForAddEdit( _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDSubsidiary", DbType:="Int")> ByVal iDSubsidiary As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDTimeLog", DbType:="BigInt")> ByVal iDTimeLog As System.Nullable(Of Long),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDUser", DbType:="Int")> ByVal iDUser As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDWorkGroup", DbType:="BigInt")> ByVal iDWorkGroup As System.Nullable(Of Long),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDEmployee", DbType:="Int")> ByVal iDEmployee As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ProductionDate", DbType:="DateTime")> ByVal productionDate As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Shift", DbType:="TinyInt")> ByVal shift As System.Nullable(Of Byte),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ShiftStart", DbType:="DateTime")> ByVal shiftStart As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ShiftEnd", DbType:="DateTime")> ByVal shiftEnd As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="WorkBreak", DbType:="Int")> ByVal workBreak As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DownTime", DbType:="Int")> ByVal downTime As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Handicap", DbType:="Float")> ByVal handicap As System.Nullable(Of Double),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="InsertedByInterface", DbType:="Bit")> ByVal insertedByInterface As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ManuallyEdited", DbType:="Bit")> ByVal manuallyEdited As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="LastEditedByIDUser", DbType:="Int")> ByVal lastEditedByIDUser As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Ticket", DbType:="DateTime")> ByVal ticket As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Deleted", DbType:="Bit")> ByVal deleted As System.Nullable(Of Boolean)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), iDSubsidiary, iDTimeLog, iDUser, iDWorkGroup, iDEmployee, productionDate, shift, shiftStart, shiftEnd, workBreak, downTime, handicap, insertedByInterface, manuallyEdited, lastEditedByIDUser, ticket, deleted)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.TimeLog_HandleAddEdit")>  _
	Public Function TimeLog_HandleAddEdit(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDSubsidiary", DbType:="Int")> ByVal iDSubsidiary As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDUser", DbType:="Int")> ByVal iDUser As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Ticket", DbType:="DateTime")> ByVal ticket As System.Nullable(Of Date)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), iDSubsidiary, iDUser, ticket)
		Return CType(result.ReturnValue,Integer)
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.TimeLog")>  _
Partial Public Class TimeLog
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDTimeLog As Long
	
	Private _IDSubsidiary As Integer
	
	Private _IDWorkGroup As Integer
	
	Private _IDWorkGroupInternal As Integer
	
	Private _IDEmployee As Integer
	
	Private _IDEmployeeInternal As Integer
	
	Private _IDBonusLists As Integer
	
	Private _IDWageGroup As Integer
	
	Private _Shift As Byte
	
	Private _ProductionDate As Date
	
	Private _ShiftStart As Date
	
	Private _ShiftStartViaInterface As System.Nullable(Of Date)
	
	Private _ShiftEnd As Date
	
	Private _ShiftEndViaInterface As System.Nullable(Of Date)
	
	Private _WorkBreak As Integer
	
	Private _WorkBreakViaInterface As System.Nullable(Of Integer)
	
	Private _DownTime As Integer
	
	Private _DownTimeViaInterface As System.Nullable(Of Integer)
	
	Private _Handicap As Double
	
	Private _AttendanceTime As Integer
	
	Private _WorkingTime As Integer
	
	Private _IncentiveWageTime As Double
	
	Private _IncentiveWageTimeAdj As Double
	
	Private _DegreeOfTime As Double
	
	Private _DegreeOfTimeAdj As Double
	
	Private _ReferenceWageTimeProRata As Double
	
	Private _InsertedByInterface As Boolean
	
	Private _ManuallyEdited As Boolean
	
	Private _IsSuspended As Boolean
	
	Private _LastEdited As Date
	
	Private _EditedByIDUser As Integer
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDTimeLogChanging(value As Long)
    End Sub
    Partial Private Sub OnIDTimeLogChanged()
    End Sub
    Partial Private Sub OnIDSubsidiaryChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDSubsidiaryChanged()
    End Sub
    Partial Private Sub OnIDWorkGroupChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDWorkGroupChanged()
    End Sub
    Partial Private Sub OnIDWorkGroupInternalChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDWorkGroupInternalChanged()
    End Sub
    Partial Private Sub OnIDEmployeeChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDEmployeeChanged()
    End Sub
    Partial Private Sub OnIDEmployeeInternalChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDEmployeeInternalChanged()
    End Sub
    Partial Private Sub OnIDBonusListsChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDBonusListsChanged()
    End Sub
    Partial Private Sub OnIDWageGroupChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDWageGroupChanged()
    End Sub
    Partial Private Sub OnShiftChanging(value As Byte)
    End Sub
    Partial Private Sub OnShiftChanged()
    End Sub
    Partial Private Sub OnProductionDateChanging(value As Date)
    End Sub
    Partial Private Sub OnProductionDateChanged()
    End Sub
    Partial Private Sub OnShiftStartChanging(value As Date)
    End Sub
    Partial Private Sub OnShiftStartChanged()
    End Sub
    Partial Private Sub OnShiftStartViaInterfaceChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnShiftStartViaInterfaceChanged()
    End Sub
    Partial Private Sub OnShiftEndChanging(value As Date)
    End Sub
    Partial Private Sub OnShiftEndChanged()
    End Sub
    Partial Private Sub OnShiftEndViaInterfaceChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnShiftEndViaInterfaceChanged()
    End Sub
    Partial Private Sub OnWorkBreakChanging(value As Integer)
    End Sub
    Partial Private Sub OnWorkBreakChanged()
    End Sub
    Partial Private Sub OnWorkBreakViaInterfaceChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnWorkBreakViaInterfaceChanged()
    End Sub
    Partial Private Sub OnDownTimeChanging(value As Integer)
    End Sub
    Partial Private Sub OnDownTimeChanged()
    End Sub
    Partial Private Sub OnDownTimeViaInterfaceChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnDownTimeViaInterfaceChanged()
    End Sub
    Partial Private Sub OnHandicapChanging(value As Double)
    End Sub
    Partial Private Sub OnHandicapChanged()
    End Sub
    Partial Private Sub OnAttendanceTimeChanging(value As Integer)
    End Sub
    Partial Private Sub OnAttendanceTimeChanged()
    End Sub
    Partial Private Sub OnWorkingTimeChanging(value As Integer)
    End Sub
    Partial Private Sub OnWorkingTimeChanged()
    End Sub
    Partial Private Sub OnIncentiveWageTimeChanging(value As Double)
    End Sub
    Partial Private Sub OnIncentiveWageTimeChanged()
    End Sub
    Partial Private Sub OnIncentiveWageTimeAdjChanging(value As Double)
    End Sub
    Partial Private Sub OnIncentiveWageTimeAdjChanged()
    End Sub
    Partial Private Sub OnDegreeOfTimeChanging(value As Double)
    End Sub
    Partial Private Sub OnDegreeOfTimeChanged()
    End Sub
    Partial Private Sub OnDegreeOfTimeAdjChanging(value As Double)
    End Sub
    Partial Private Sub OnDegreeOfTimeAdjChanged()
    End Sub
    Partial Private Sub OnReferenceWageTimeProRataChanging(value As Double)
    End Sub
    Partial Private Sub OnReferenceWageTimeProRataChanged()
    End Sub
    Partial Private Sub OnInsertedByInterfaceChanging(value As Boolean)
    End Sub
    Partial Private Sub OnInsertedByInterfaceChanged()
    End Sub
    Partial Private Sub OnManuallyEditedChanging(value As Boolean)
    End Sub
    Partial Private Sub OnManuallyEditedChanged()
    End Sub
    Partial Private Sub OnIsSuspendedChanging(value As Boolean)
    End Sub
    Partial Private Sub OnIsSuspendedChanged()
    End Sub
    Partial Private Sub OnLastEditedChanging(value As Date)
    End Sub
    Partial Private Sub OnLastEditedChanged()
    End Sub
    Partial Private Sub OnEditedByIDUserChanging(value As Integer)
    End Sub
    Partial Private Sub OnEditedByIDUserChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDTimeLog", AutoSync:=AutoSync.OnInsert, DbType:="BigInt NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDTimeLog() As Long
		Get
			Return Me._IDTimeLog
		End Get
		Set
			If ((Me._IDTimeLog = value)  _
						= false) Then
				Me.OnIDTimeLogChanging(value)
				Me.SendPropertyChanging
				Me._IDTimeLog = value
				Me.SendPropertyChanged("IDTimeLog")
				Me.OnIDTimeLogChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDSubsidiary", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property IDSubsidiary() As Integer
		Get
			Return Me._IDSubsidiary
		End Get
		Set
			If ((Me._IDSubsidiary = value)  _
						= false) Then
				Me.OnIDSubsidiaryChanging(value)
				Me.SendPropertyChanging
				Me._IDSubsidiary = value
				Me.SendPropertyChanged("IDSubsidiary")
				Me.OnIDSubsidiaryChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDWorkGroup", DbType:="Int NOT NULL")>  _
	Public Property IDWorkGroup() As Integer
		Get
			Return Me._IDWorkGroup
		End Get
		Set
			If ((Me._IDWorkGroup = value)  _
						= false) Then
				Me.OnIDWorkGroupChanging(value)
				Me.SendPropertyChanging
				Me._IDWorkGroup = value
				Me.SendPropertyChanged("IDWorkGroup")
				Me.OnIDWorkGroupChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDWorkGroupInternal", DbType:="Int NOT NULL")>  _
	Public Property IDWorkGroupInternal() As Integer
		Get
			Return Me._IDWorkGroupInternal
		End Get
		Set
			If ((Me._IDWorkGroupInternal = value)  _
						= false) Then
				Me.OnIDWorkGroupInternalChanging(value)
				Me.SendPropertyChanging
				Me._IDWorkGroupInternal = value
				Me.SendPropertyChanged("IDWorkGroupInternal")
				Me.OnIDWorkGroupInternalChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDEmployee", DbType:="Int NOT NULL")>  _
	Public Property IDEmployee() As Integer
		Get
			Return Me._IDEmployee
		End Get
		Set
			If ((Me._IDEmployee = value)  _
						= false) Then
				Me.OnIDEmployeeChanging(value)
				Me.SendPropertyChanging
				Me._IDEmployee = value
				Me.SendPropertyChanged("IDEmployee")
				Me.OnIDEmployeeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDEmployeeInternal", DbType:="Int NOT NULL")>  _
	Public Property IDEmployeeInternal() As Integer
		Get
			Return Me._IDEmployeeInternal
		End Get
		Set
			If ((Me._IDEmployeeInternal = value)  _
						= false) Then
				Me.OnIDEmployeeInternalChanging(value)
				Me.SendPropertyChanging
				Me._IDEmployeeInternal = value
				Me.SendPropertyChanged("IDEmployeeInternal")
				Me.OnIDEmployeeInternalChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDBonusLists", DbType:="Int NOT NULL")>  _
	Public Property IDBonusLists() As Integer
		Get
			Return Me._IDBonusLists
		End Get
		Set
			If ((Me._IDBonusLists = value)  _
						= false) Then
				Me.OnIDBonusListsChanging(value)
				Me.SendPropertyChanging
				Me._IDBonusLists = value
				Me.SendPropertyChanged("IDBonusLists")
				Me.OnIDBonusListsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDWageGroup", DbType:="Int NOT NULL")>  _
	Public Property IDWageGroup() As Integer
		Get
			Return Me._IDWageGroup
		End Get
		Set
			If ((Me._IDWageGroup = value)  _
						= false) Then
				Me.OnIDWageGroupChanging(value)
				Me.SendPropertyChanging
				Me._IDWageGroup = value
				Me.SendPropertyChanged("IDWageGroup")
				Me.OnIDWageGroupChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Shift", DbType:="TinyInt NOT NULL")>  _
	Public Property Shift() As Byte
		Get
			Return Me._Shift
		End Get
		Set
			If ((Me._Shift = value)  _
						= false) Then
				Me.OnShiftChanging(value)
				Me.SendPropertyChanging
				Me._Shift = value
				Me.SendPropertyChanged("Shift")
				Me.OnShiftChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProductionDate", DbType:="DateTime NOT NULL")>  _
	Public Property ProductionDate() As Date
		Get
			Return Me._ProductionDate
		End Get
		Set
			If ((Me._ProductionDate = value)  _
						= false) Then
				Me.OnProductionDateChanging(value)
				Me.SendPropertyChanging
				Me._ProductionDate = value
				Me.SendPropertyChanged("ProductionDate")
				Me.OnProductionDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShiftStart", DbType:="DateTime NOT NULL")>  _
	Public Property ShiftStart() As Date
		Get
			Return Me._ShiftStart
		End Get
		Set
			If ((Me._ShiftStart = value)  _
						= false) Then
				Me.OnShiftStartChanging(value)
				Me.SendPropertyChanging
				Me._ShiftStart = value
				Me.SendPropertyChanged("ShiftStart")
				Me.OnShiftStartChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShiftStartViaInterface", DbType:="DateTime")>  _
	Public Property ShiftStartViaInterface() As System.Nullable(Of Date)
		Get
			Return Me._ShiftStartViaInterface
		End Get
		Set
			If (Me._ShiftStartViaInterface.Equals(value) = false) Then
				Me.OnShiftStartViaInterfaceChanging(value)
				Me.SendPropertyChanging
				Me._ShiftStartViaInterface = value
				Me.SendPropertyChanged("ShiftStartViaInterface")
				Me.OnShiftStartViaInterfaceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShiftEnd", DbType:="DateTime NOT NULL")>  _
	Public Property ShiftEnd() As Date
		Get
			Return Me._ShiftEnd
		End Get
		Set
			If ((Me._ShiftEnd = value)  _
						= false) Then
				Me.OnShiftEndChanging(value)
				Me.SendPropertyChanging
				Me._ShiftEnd = value
				Me.SendPropertyChanged("ShiftEnd")
				Me.OnShiftEndChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShiftEndViaInterface", DbType:="DateTime")>  _
	Public Property ShiftEndViaInterface() As System.Nullable(Of Date)
		Get
			Return Me._ShiftEndViaInterface
		End Get
		Set
			If (Me._ShiftEndViaInterface.Equals(value) = false) Then
				Me.OnShiftEndViaInterfaceChanging(value)
				Me.SendPropertyChanging
				Me._ShiftEndViaInterface = value
				Me.SendPropertyChanged("ShiftEndViaInterface")
				Me.OnShiftEndViaInterfaceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WorkBreak", DbType:="Int NOT NULL")>  _
	Public Property WorkBreak() As Integer
		Get
			Return Me._WorkBreak
		End Get
		Set
			If ((Me._WorkBreak = value)  _
						= false) Then
				Me.OnWorkBreakChanging(value)
				Me.SendPropertyChanging
				Me._WorkBreak = value
				Me.SendPropertyChanged("WorkBreak")
				Me.OnWorkBreakChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WorkBreakViaInterface", DbType:="Int")>  _
	Public Property WorkBreakViaInterface() As System.Nullable(Of Integer)
		Get
			Return Me._WorkBreakViaInterface
		End Get
		Set
			If (Me._WorkBreakViaInterface.Equals(value) = false) Then
				Me.OnWorkBreakViaInterfaceChanging(value)
				Me.SendPropertyChanging
				Me._WorkBreakViaInterface = value
				Me.SendPropertyChanged("WorkBreakViaInterface")
				Me.OnWorkBreakViaInterfaceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DownTime", DbType:="Int NOT NULL")>  _
	Public Property DownTime() As Integer
		Get
			Return Me._DownTime
		End Get
		Set
			If ((Me._DownTime = value)  _
						= false) Then
				Me.OnDownTimeChanging(value)
				Me.SendPropertyChanging
				Me._DownTime = value
				Me.SendPropertyChanged("DownTime")
				Me.OnDownTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DownTimeViaInterface", DbType:="Int")>  _
	Public Property DownTimeViaInterface() As System.Nullable(Of Integer)
		Get
			Return Me._DownTimeViaInterface
		End Get
		Set
			If (Me._DownTimeViaInterface.Equals(value) = false) Then
				Me.OnDownTimeViaInterfaceChanging(value)
				Me.SendPropertyChanging
				Me._DownTimeViaInterface = value
				Me.SendPropertyChanged("DownTimeViaInterface")
				Me.OnDownTimeViaInterfaceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Handicap", DbType:="Float NOT NULL")>  _
	Public Property Handicap() As Double
		Get
			Return Me._Handicap
		End Get
		Set
			If ((Me._Handicap = value)  _
						= false) Then
				Me.OnHandicapChanging(value)
				Me.SendPropertyChanging
				Me._Handicap = value
				Me.SendPropertyChanged("Handicap")
				Me.OnHandicapChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AttendanceTime", DbType:="Int NOT NULL")>  _
	Public Property AttendanceTime() As Integer
		Get
			Return Me._AttendanceTime
		End Get
		Set
			If ((Me._AttendanceTime = value)  _
						= false) Then
				Me.OnAttendanceTimeChanging(value)
				Me.SendPropertyChanging
				Me._AttendanceTime = value
				Me.SendPropertyChanged("AttendanceTime")
				Me.OnAttendanceTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WorkingTime", DbType:="Int NOT NULL")>  _
	Public Property WorkingTime() As Integer
		Get
			Return Me._WorkingTime
		End Get
		Set
			If ((Me._WorkingTime = value)  _
						= false) Then
				Me.OnWorkingTimeChanging(value)
				Me.SendPropertyChanging
				Me._WorkingTime = value
				Me.SendPropertyChanged("WorkingTime")
				Me.OnWorkingTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IncentiveWageTime", DbType:="Float NOT NULL")>  _
	Public Property IncentiveWageTime() As Double
		Get
			Return Me._IncentiveWageTime
		End Get
		Set
			If ((Me._IncentiveWageTime = value)  _
						= false) Then
				Me.OnIncentiveWageTimeChanging(value)
				Me.SendPropertyChanging
				Me._IncentiveWageTime = value
				Me.SendPropertyChanged("IncentiveWageTime")
				Me.OnIncentiveWageTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IncentiveWageTimeAdj", DbType:="Float NOT NULL")>  _
	Public Property IncentiveWageTimeAdj() As Double
		Get
			Return Me._IncentiveWageTimeAdj
		End Get
		Set
			If ((Me._IncentiveWageTimeAdj = value)  _
						= false) Then
				Me.OnIncentiveWageTimeAdjChanging(value)
				Me.SendPropertyChanging
				Me._IncentiveWageTimeAdj = value
				Me.SendPropertyChanged("IncentiveWageTimeAdj")
				Me.OnIncentiveWageTimeAdjChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DegreeOfTime", DbType:="Float NOT NULL")>  _
	Public Property DegreeOfTime() As Double
		Get
			Return Me._DegreeOfTime
		End Get
		Set
			If ((Me._DegreeOfTime = value)  _
						= false) Then
				Me.OnDegreeOfTimeChanging(value)
				Me.SendPropertyChanging
				Me._DegreeOfTime = value
				Me.SendPropertyChanged("DegreeOfTime")
				Me.OnDegreeOfTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DegreeOfTimeAdj", DbType:="Float NOT NULL")>  _
	Public Property DegreeOfTimeAdj() As Double
		Get
			Return Me._DegreeOfTimeAdj
		End Get
		Set
			If ((Me._DegreeOfTimeAdj = value)  _
						= false) Then
				Me.OnDegreeOfTimeAdjChanging(value)
				Me.SendPropertyChanging
				Me._DegreeOfTimeAdj = value
				Me.SendPropertyChanged("DegreeOfTimeAdj")
				Me.OnDegreeOfTimeAdjChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ReferenceWageTimeProRata", DbType:="Float NOT NULL")>  _
	Public Property ReferenceWageTimeProRata() As Double
		Get
			Return Me._ReferenceWageTimeProRata
		End Get
		Set
			If ((Me._ReferenceWageTimeProRata = value)  _
						= false) Then
				Me.OnReferenceWageTimeProRataChanging(value)
				Me.SendPropertyChanging
				Me._ReferenceWageTimeProRata = value
				Me.SendPropertyChanged("ReferenceWageTimeProRata")
				Me.OnReferenceWageTimeProRataChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsertedByInterface", DbType:="Bit NOT NULL")>  _
	Public Property InsertedByInterface() As Boolean
		Get
			Return Me._InsertedByInterface
		End Get
		Set
			If ((Me._InsertedByInterface = value)  _
						= false) Then
				Me.OnInsertedByInterfaceChanging(value)
				Me.SendPropertyChanging
				Me._InsertedByInterface = value
				Me.SendPropertyChanged("InsertedByInterface")
				Me.OnInsertedByInterfaceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ManuallyEdited", DbType:="Bit NOT NULL")>  _
	Public Property ManuallyEdited() As Boolean
		Get
			Return Me._ManuallyEdited
		End Get
		Set
			If ((Me._ManuallyEdited = value)  _
						= false) Then
				Me.OnManuallyEditedChanging(value)
				Me.SendPropertyChanging
				Me._ManuallyEdited = value
				Me.SendPropertyChanged("ManuallyEdited")
				Me.OnManuallyEditedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsSuspended", DbType:="Bit NOT NULL")>  _
	Public Property IsSuspended() As Boolean
		Get
			Return Me._IsSuspended
		End Get
		Set
			If ((Me._IsSuspended = value)  _
						= false) Then
				Me.OnIsSuspendedChanging(value)
				Me.SendPropertyChanging
				Me._IsSuspended = value
				Me.SendPropertyChanged("IsSuspended")
				Me.OnIsSuspendedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastEdited", DbType:="DateTime NOT NULL")>  _
	Public Property LastEdited() As Date
		Get
			Return Me._LastEdited
		End Get
		Set
			If ((Me._LastEdited = value)  _
						= false) Then
				Me.OnLastEditedChanging(value)
				Me.SendPropertyChanging
				Me._LastEdited = value
				Me.SendPropertyChanged("LastEdited")
				Me.OnLastEditedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EditedByIDUser", DbType:="Int NOT NULL")>  _
	Public Property EditedByIDUser() As Integer
		Get
			Return Me._EditedByIDUser
		End Get
		Set
			If ((Me._EditedByIDUser = value)  _
						= false) Then
				Me.OnEditedByIDUserChanging(value)
				Me.SendPropertyChanging
				Me._EditedByIDUser = value
				Me.SendPropertyChanged("EditedByIDUser")
				Me.OnEditedByIDUserChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
