'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Facesso.Data.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kostenstellenbeschreibung.
        '''</summary>
        Friend ReadOnly Property CostCenterInfo_ColumnCaption_Description() As String
            Get
                Return ResourceManager.GetString("CostCenterInfo_ColumnCaption_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kostenstellenname.
        '''</summary>
        Friend ReadOnly Property CostCenterInfo_ColumnCaption_Name() As String
            Get
                Return ResourceManager.GetString("CostCenterInfo_ColumnCaption_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kostenstellennr.
        '''</summary>
        Friend ReadOnly Property CostCenterInfo_ColumnCaption_No() As String
            Get
                Return ResourceManager.GetString("CostCenterInfo_ColumnCaption_No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT     ProductionDataItems.IDSubsidiary, ProductionDataItems.IDLabourValue, SUM(ProductionDataItems.Amount) AS AmountTotal, 
        '''                      LabourValues.LabourValueName, LabourValues.LabourValueNumber, LabourValues.TeHMin, LabourValues.Dimension, 
        '''                      LabourValues.LabourValueDescription, CostCenters.CostCenterNo, CostCenters.CostCenterName, LabourValues.IDCostCenter, 
        '''                      LabourValues.IDLabourValueInternal, LabourValues.WasCurrentFrom, LabourValues.WasCurren [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SELECT_ProductionDataAmount() As String
            Get
                Return ResourceManager.GetString("SELECT_ProductionDataAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Funktionsinstanz für den Zugriff auf die Datenbank konnte wegen fehlernder Lizenz nicht erstellt werden!.
        '''</summary>
        Friend ReadOnly Property Sp_Main_FailedInstancingDueToLicence() As String
            Get
                Return ResourceManager.GetString("Sp_Main_FailedInstancingDueToLicence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beim Versuch, die Facesso-Datenbank zu öffnen, ist ein Fehler aufgetreten!.
        '''</summary>
        Friend ReadOnly Property Sp_Main_OpenFacessoConnectionFailed() As String
            Get
                Return ResourceManager.GetString("Sp_Main_OpenFacessoConnectionFailed", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
