'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Legatro")>  _
Partial Public Class LegatroDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertWorksitesOrProjects(instance As WorksitesOrProjects)
    End Sub
  Partial Private Sub UpdateWorksitesOrProjects(instance As WorksitesOrProjects)
    End Sub
  Partial Private Sub DeleteWorksitesOrProjects(instance As WorksitesOrProjects)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.Facesso.Interfaces.My.MySettings.Default.LegatroConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property ViewFlatTimes() As System.Data.Linq.Table(Of ViewFlatTimes)
		Get
			Return Me.GetTable(Of ViewFlatTimes)
		End Get
	End Property
	
	Public ReadOnly Property ViewTimeLogNativeVerbatim() As System.Data.Linq.Table(Of ViewTimeLogNativeVerbatim)
		Get
			Return Me.GetTable(Of ViewTimeLogNativeVerbatim)
		End Get
	End Property
	
	Public ReadOnly Property WorksitesOrProjects() As System.Data.Linq.Table(Of WorksitesOrProjects)
		Get
			Return Me.GetTable(Of WorksitesOrProjects)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ViewFlatTimes")>  _
Partial Public Class ViewFlatTimes
	
	Private _StartTime As System.Nullable(Of Date)
	
	Private _EndTime As System.Nullable(Of Date)
	
	Private _Duration As System.Nullable(Of Integer)
	
	Private _PersonnelNumber As System.Nullable(Of Integer)
	
	Private _LastName As String
	
	Private _FirstName As String
	
	Private _MiddleName As String
	
	Private _WorkEntityName As String
	
	Private _WorkEntityNumber As System.Nullable(Of Integer)
	
	Private _CostCenterNo As System.Nullable(Of Integer)
	
	Private _CostCenterName As String
	
	Private _TimeLogEventName As String
	
	Private _IDTimeLogFlat As System.Guid
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StartTime", DbType:="DateTime")>  _
	Public Property StartTime() As System.Nullable(Of Date)
		Get
			Return Me._StartTime
		End Get
		Set
			If (Me._StartTime.Equals(value) = false) Then
				Me._StartTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EndTime", DbType:="DateTime")>  _
	Public Property EndTime() As System.Nullable(Of Date)
		Get
			Return Me._EndTime
		End Get
		Set
			If (Me._EndTime.Equals(value) = false) Then
				Me._EndTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Duration", DbType:="Int")>  _
	Public Property Duration() As System.Nullable(Of Integer)
		Get
			Return Me._Duration
		End Get
		Set
			If (Me._Duration.Equals(value) = false) Then
				Me._Duration = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PersonnelNumber", DbType:="Int")>  _
	Public Property PersonnelNumber() As System.Nullable(Of Integer)
		Get
			Return Me._PersonnelNumber
		End Get
		Set
			If (Me._PersonnelNumber.Equals(value) = false) Then
				Me._PersonnelNumber = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastName", DbType:="NVarChar(100)")>  _
	Public Property LastName() As String
		Get
			Return Me._LastName
		End Get
		Set
			If (String.Equals(Me._LastName, value) = false) Then
				Me._LastName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FirstName", DbType:="NVarChar(100)")>  _
	Public Property FirstName() As String
		Get
			Return Me._FirstName
		End Get
		Set
			If (String.Equals(Me._FirstName, value) = false) Then
				Me._FirstName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MiddleName", DbType:="NVarChar(100)")>  _
	Public Property MiddleName() As String
		Get
			Return Me._MiddleName
		End Get
		Set
			If (String.Equals(Me._MiddleName, value) = false) Then
				Me._MiddleName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WorkEntityName", DbType:="NVarChar(255)")>  _
	Public Property WorkEntityName() As String
		Get
			Return Me._WorkEntityName
		End Get
		Set
			If (String.Equals(Me._WorkEntityName, value) = false) Then
				Me._WorkEntityName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WorkEntityNumber", DbType:="Int")>  _
	Public Property WorkEntityNumber() As System.Nullable(Of Integer)
		Get
			Return Me._WorkEntityNumber
		End Get
		Set
			If (Me._WorkEntityNumber.Equals(value) = false) Then
				Me._WorkEntityNumber = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CostCenterNo", DbType:="Int")>  _
	Public Property CostCenterNo() As System.Nullable(Of Integer)
		Get
			Return Me._CostCenterNo
		End Get
		Set
			If (Me._CostCenterNo.Equals(value) = false) Then
				Me._CostCenterNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CostCenterName", DbType:="NVarChar(100)")>  _
	Public Property CostCenterName() As String
		Get
			Return Me._CostCenterName
		End Get
		Set
			If (String.Equals(Me._CostCenterName, value) = false) Then
				Me._CostCenterName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TimeLogEventName", DbType:="NVarChar(50)")>  _
	Public Property TimeLogEventName() As String
		Get
			Return Me._TimeLogEventName
		End Get
		Set
			If (String.Equals(Me._TimeLogEventName, value) = false) Then
				Me._TimeLogEventName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDTimeLogFlat", DbType:="UniqueIdentifier NOT NULL")>  _
	Public Property IDTimeLogFlat() As System.Guid
		Get
			Return Me._IDTimeLogFlat
		End Get
		Set
			If ((Me._IDTimeLogFlat = value)  _
						= false) Then
				Me._IDTimeLogFlat = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ViewTimeLogNativeVerbatim")>  _
Partial Public Class ViewTimeLogNativeVerbatim
	
	Private _IDTimeLogNative As System.Nullable(Of System.Guid)
	
	Private _PersonnelNumber As Integer
	
	Private _LastName As String
	
	Private _FirstName As String
	
	Private _MiddleName As String
	
	Private _Matchcode As String
	
	Private _CombinedName As String
	
	Private _BookingType As Short
	
	Private _TimeLogEventName As String
	
	Private _WorkEntityName As String
	
	Private _WorkEntityNumber As System.Nullable(Of Integer)
	
	Private _IDTimeLogNativeEditable As System.Nullable(Of System.Guid)
	
	Private _IDTimeLogEventType As System.Nullable(Of System.Guid)
	
	Private _IDWorksiteOrProject As System.Nullable(Of System.Guid)
	
	Private _IDEmployee As System.Nullable(Of System.Guid)
	
	Private _IDOrder As System.Nullable(Of System.Guid)
	
	Private _IDTimeLogDevice As System.Nullable(Of System.Guid)
	
	Private _EventTime As System.Nullable(Of Date)
	
	Private _IDTimeLogFlat As System.Nullable(Of System.Guid)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDTimeLogNative", DbType:="UniqueIdentifier")>  _
	Public Property IDTimeLogNative() As System.Nullable(Of System.Guid)
		Get
			Return Me._IDTimeLogNative
		End Get
		Set
			If (Me._IDTimeLogNative.Equals(value) = false) Then
				Me._IDTimeLogNative = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PersonnelNumber", DbType:="Int NOT NULL")>  _
	Public Property PersonnelNumber() As Integer
		Get
			Return Me._PersonnelNumber
		End Get
		Set
			If ((Me._PersonnelNumber = value)  _
						= false) Then
				Me._PersonnelNumber = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastName", DbType:="NVarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property LastName() As String
		Get
			Return Me._LastName
		End Get
		Set
			If (String.Equals(Me._LastName, value) = false) Then
				Me._LastName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FirstName", DbType:="NVarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property FirstName() As String
		Get
			Return Me._FirstName
		End Get
		Set
			If (String.Equals(Me._FirstName, value) = false) Then
				Me._FirstName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MiddleName", DbType:="NVarChar(100)")>  _
	Public Property MiddleName() As String
		Get
			Return Me._MiddleName
		End Get
		Set
			If (String.Equals(Me._MiddleName, value) = false) Then
				Me._MiddleName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Matchcode", DbType:="NVarChar(50)")>  _
	Public Property Matchcode() As String
		Get
			Return Me._Matchcode
		End Get
		Set
			If (String.Equals(Me._Matchcode, value) = false) Then
				Me._Matchcode = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CombinedName", DbType:="NVarChar(202) NOT NULL", CanBeNull:=false)>  _
	Public Property CombinedName() As String
		Get
			Return Me._CombinedName
		End Get
		Set
			If (String.Equals(Me._CombinedName, value) = false) Then
				Me._CombinedName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BookingType", DbType:="SmallInt NOT NULL")>  _
	Public Property BookingType() As Short
		Get
			Return Me._BookingType
		End Get
		Set
			If ((Me._BookingType = value)  _
						= false) Then
				Me._BookingType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TimeLogEventName", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property TimeLogEventName() As String
		Get
			Return Me._TimeLogEventName
		End Get
		Set
			If (String.Equals(Me._TimeLogEventName, value) = false) Then
				Me._TimeLogEventName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WorkEntityName", DbType:="NVarChar(255)")>  _
	Public Property WorkEntityName() As String
		Get
			Return Me._WorkEntityName
		End Get
		Set
			If (String.Equals(Me._WorkEntityName, value) = false) Then
				Me._WorkEntityName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WorkEntityNumber", DbType:="Int")>  _
	Public Property WorkEntityNumber() As System.Nullable(Of Integer)
		Get
			Return Me._WorkEntityNumber
		End Get
		Set
			If (Me._WorkEntityNumber.Equals(value) = false) Then
				Me._WorkEntityNumber = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDTimeLogNativeEditable", DbType:="UniqueIdentifier")>  _
	Public Property IDTimeLogNativeEditable() As System.Nullable(Of System.Guid)
		Get
			Return Me._IDTimeLogNativeEditable
		End Get
		Set
			If (Me._IDTimeLogNativeEditable.Equals(value) = false) Then
				Me._IDTimeLogNativeEditable = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDTimeLogEventType", DbType:="UniqueIdentifier")>  _
	Public Property IDTimeLogEventType() As System.Nullable(Of System.Guid)
		Get
			Return Me._IDTimeLogEventType
		End Get
		Set
			If (Me._IDTimeLogEventType.Equals(value) = false) Then
				Me._IDTimeLogEventType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDWorksiteOrProject", DbType:="UniqueIdentifier")>  _
	Public Property IDWorksiteOrProject() As System.Nullable(Of System.Guid)
		Get
			Return Me._IDWorksiteOrProject
		End Get
		Set
			If (Me._IDWorksiteOrProject.Equals(value) = false) Then
				Me._IDWorksiteOrProject = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDEmployee", DbType:="UniqueIdentifier")>  _
	Public Property IDEmployee() As System.Nullable(Of System.Guid)
		Get
			Return Me._IDEmployee
		End Get
		Set
			If (Me._IDEmployee.Equals(value) = false) Then
				Me._IDEmployee = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDOrder", DbType:="UniqueIdentifier")>  _
	Public Property IDOrder() As System.Nullable(Of System.Guid)
		Get
			Return Me._IDOrder
		End Get
		Set
			If (Me._IDOrder.Equals(value) = false) Then
				Me._IDOrder = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDTimeLogDevice", DbType:="UniqueIdentifier")>  _
	Public Property IDTimeLogDevice() As System.Nullable(Of System.Guid)
		Get
			Return Me._IDTimeLogDevice
		End Get
		Set
			If (Me._IDTimeLogDevice.Equals(value) = false) Then
				Me._IDTimeLogDevice = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EventTime", DbType:="DateTime")>  _
	Public Property EventTime() As System.Nullable(Of Date)
		Get
			Return Me._EventTime
		End Get
		Set
			If (Me._EventTime.Equals(value) = false) Then
				Me._EventTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDTimeLogFlat", DbType:="UniqueIdentifier")>  _
	Public Property IDTimeLogFlat() As System.Nullable(Of System.Guid)
		Get
			Return Me._IDTimeLogFlat
		End Get
		Set
			If (Me._IDTimeLogFlat.Equals(value) = false) Then
				Me._IDTimeLogFlat = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.WorksitesOrProjects")>  _
Partial Public Class WorksitesOrProjects
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDWorksiteOrProject As System.Guid
	
	Private _IDCostCenter As System.Guid
	
	Private _IDUserAsOwner As System.Nullable(Of System.Guid)
	
	Private _IDCustomer As System.Nullable(Of System.Guid)
	
	Private _IDContactForWorksiteOrProject As System.Nullable(Of System.Guid)
	
	Private _IDCostObjects As System.Guid
	
	Private _WorkEntityNumber As Integer
	
	Private _WorkEntityName As String
	
	Private _ShortWorkEntityName As String
	
	Private _IsProject As Boolean
	
	Private _IsActive As Boolean
	
	Private _Description As String
	
	Private _MonitorTimeCapacity As System.Nullable(Of Boolean)
	
	Private _MonthlyTargetTimeCapacity As System.Nullable(Of Integer)
	
	Private _MonitorStartdate As System.Nullable(Of Date)
	
	Private _MonitorEnddate As System.Nullable(Of Date)
	
	Private _TotalTargetTimeCapacity As System.Nullable(Of Integer)
	
	Private _CollectProductionUnits As Boolean
	
	Private _CollectProductionUnitsDescription As Boolean
	
	Private _LastEditDate As Date
	
	Private _CreationDate As Date
	
	Private _SyncGuid As System.Guid
	
	Private _IsDeleted As Boolean
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDWorksiteOrProjectChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnIDWorksiteOrProjectChanged()
    End Sub
    Partial Private Sub OnIDCostCenterChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnIDCostCenterChanged()
    End Sub
    Partial Private Sub OnIDUserAsOwnerChanging(value As System.Nullable(Of System.Guid))
    End Sub
    Partial Private Sub OnIDUserAsOwnerChanged()
    End Sub
    Partial Private Sub OnIDCustomerChanging(value As System.Nullable(Of System.Guid))
    End Sub
    Partial Private Sub OnIDCustomerChanged()
    End Sub
    Partial Private Sub OnIDContactForWorksiteOrProjectChanging(value As System.Nullable(Of System.Guid))
    End Sub
    Partial Private Sub OnIDContactForWorksiteOrProjectChanged()
    End Sub
    Partial Private Sub OnIDCostObjectsChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnIDCostObjectsChanged()
    End Sub
    Partial Private Sub OnWorkEntityNumberChanging(value As Integer)
    End Sub
    Partial Private Sub OnWorkEntityNumberChanged()
    End Sub
    Partial Private Sub OnWorkEntityNameChanging(value As String)
    End Sub
    Partial Private Sub OnWorkEntityNameChanged()
    End Sub
    Partial Private Sub OnShortWorkEntityNameChanging(value As String)
    End Sub
    Partial Private Sub OnShortWorkEntityNameChanged()
    End Sub
    Partial Private Sub OnIsProjectChanging(value As Boolean)
    End Sub
    Partial Private Sub OnIsProjectChanged()
    End Sub
    Partial Private Sub OnIsActiveChanging(value As Boolean)
    End Sub
    Partial Private Sub OnIsActiveChanged()
    End Sub
    Partial Private Sub OnDescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnDescriptionChanged()
    End Sub
    Partial Private Sub OnMonitorTimeCapacityChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnMonitorTimeCapacityChanged()
    End Sub
    Partial Private Sub OnMonthlyTargetTimeCapacityChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnMonthlyTargetTimeCapacityChanged()
    End Sub
    Partial Private Sub OnMonitorStartdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnMonitorStartdateChanged()
    End Sub
    Partial Private Sub OnMonitorEnddateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnMonitorEnddateChanged()
    End Sub
    Partial Private Sub OnTotalTargetTimeCapacityChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTotalTargetTimeCapacityChanged()
    End Sub
    Partial Private Sub OnCollectProductionUnitsChanging(value As Boolean)
    End Sub
    Partial Private Sub OnCollectProductionUnitsChanged()
    End Sub
    Partial Private Sub OnCollectProductionUnitsDescriptionChanging(value As Boolean)
    End Sub
    Partial Private Sub OnCollectProductionUnitsDescriptionChanged()
    End Sub
    Partial Private Sub OnLastEditDateChanging(value As Date)
    End Sub
    Partial Private Sub OnLastEditDateChanged()
    End Sub
    Partial Private Sub OnCreationDateChanging(value As Date)
    End Sub
    Partial Private Sub OnCreationDateChanged()
    End Sub
    Partial Private Sub OnSyncGuidChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnSyncGuidChanged()
    End Sub
    Partial Private Sub OnIsDeletedChanging(value As Boolean)
    End Sub
    Partial Private Sub OnIsDeletedChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDWorksiteOrProject", DbType:="UniqueIdentifier NOT NULL", IsPrimaryKey:=true)>  _
	Public Property IDWorksiteOrProject() As System.Guid
		Get
			Return Me._IDWorksiteOrProject
		End Get
		Set
			If ((Me._IDWorksiteOrProject = value)  _
						= false) Then
				Me.OnIDWorksiteOrProjectChanging(value)
				Me.SendPropertyChanging
				Me._IDWorksiteOrProject = value
				Me.SendPropertyChanged("IDWorksiteOrProject")
				Me.OnIDWorksiteOrProjectChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDCostCenter", DbType:="UniqueIdentifier NOT NULL")>  _
	Public Property IDCostCenter() As System.Guid
		Get
			Return Me._IDCostCenter
		End Get
		Set
			If ((Me._IDCostCenter = value)  _
						= false) Then
				Me.OnIDCostCenterChanging(value)
				Me.SendPropertyChanging
				Me._IDCostCenter = value
				Me.SendPropertyChanged("IDCostCenter")
				Me.OnIDCostCenterChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDUserAsOwner", DbType:="UniqueIdentifier")>  _
	Public Property IDUserAsOwner() As System.Nullable(Of System.Guid)
		Get
			Return Me._IDUserAsOwner
		End Get
		Set
			If (Me._IDUserAsOwner.Equals(value) = false) Then
				Me.OnIDUserAsOwnerChanging(value)
				Me.SendPropertyChanging
				Me._IDUserAsOwner = value
				Me.SendPropertyChanged("IDUserAsOwner")
				Me.OnIDUserAsOwnerChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDCustomer", DbType:="UniqueIdentifier")>  _
	Public Property IDCustomer() As System.Nullable(Of System.Guid)
		Get
			Return Me._IDCustomer
		End Get
		Set
			If (Me._IDCustomer.Equals(value) = false) Then
				Me.OnIDCustomerChanging(value)
				Me.SendPropertyChanging
				Me._IDCustomer = value
				Me.SendPropertyChanged("IDCustomer")
				Me.OnIDCustomerChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDContactForWorksiteOrProject", DbType:="UniqueIdentifier")>  _
	Public Property IDContactForWorksiteOrProject() As System.Nullable(Of System.Guid)
		Get
			Return Me._IDContactForWorksiteOrProject
		End Get
		Set
			If (Me._IDContactForWorksiteOrProject.Equals(value) = false) Then
				Me.OnIDContactForWorksiteOrProjectChanging(value)
				Me.SendPropertyChanging
				Me._IDContactForWorksiteOrProject = value
				Me.SendPropertyChanged("IDContactForWorksiteOrProject")
				Me.OnIDContactForWorksiteOrProjectChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDCostObjects", DbType:="UniqueIdentifier NOT NULL")>  _
	Public Property IDCostObjects() As System.Guid
		Get
			Return Me._IDCostObjects
		End Get
		Set
			If ((Me._IDCostObjects = value)  _
						= false) Then
				Me.OnIDCostObjectsChanging(value)
				Me.SendPropertyChanging
				Me._IDCostObjects = value
				Me.SendPropertyChanged("IDCostObjects")
				Me.OnIDCostObjectsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WorkEntityNumber", DbType:="Int NOT NULL")>  _
	Public Property WorkEntityNumber() As Integer
		Get
			Return Me._WorkEntityNumber
		End Get
		Set
			If ((Me._WorkEntityNumber = value)  _
						= false) Then
				Me.OnWorkEntityNumberChanging(value)
				Me.SendPropertyChanging
				Me._WorkEntityNumber = value
				Me.SendPropertyChanged("WorkEntityNumber")
				Me.OnWorkEntityNumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WorkEntityName", DbType:="NVarChar(255) NOT NULL", CanBeNull:=false)>  _
	Public Property WorkEntityName() As String
		Get
			Return Me._WorkEntityName
		End Get
		Set
			If (String.Equals(Me._WorkEntityName, value) = false) Then
				Me.OnWorkEntityNameChanging(value)
				Me.SendPropertyChanging
				Me._WorkEntityName = value
				Me.SendPropertyChanged("WorkEntityName")
				Me.OnWorkEntityNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShortWorkEntityName", DbType:="NVarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property ShortWorkEntityName() As String
		Get
			Return Me._ShortWorkEntityName
		End Get
		Set
			If (String.Equals(Me._ShortWorkEntityName, value) = false) Then
				Me.OnShortWorkEntityNameChanging(value)
				Me.SendPropertyChanging
				Me._ShortWorkEntityName = value
				Me.SendPropertyChanged("ShortWorkEntityName")
				Me.OnShortWorkEntityNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsProject", DbType:="Bit NOT NULL")>  _
	Public Property IsProject() As Boolean
		Get
			Return Me._IsProject
		End Get
		Set
			If ((Me._IsProject = value)  _
						= false) Then
				Me.OnIsProjectChanging(value)
				Me.SendPropertyChanging
				Me._IsProject = value
				Me.SendPropertyChanged("IsProject")
				Me.OnIsProjectChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsActive", DbType:="Bit NOT NULL")>  _
	Public Property IsActive() As Boolean
		Get
			Return Me._IsActive
		End Get
		Set
			If ((Me._IsActive = value)  _
						= false) Then
				Me.OnIsActiveChanging(value)
				Me.SendPropertyChanging
				Me._IsActive = value
				Me.SendPropertyChanged("IsActive")
				Me.OnIsActiveChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Description", DbType:="NVarChar(3000)")>  _
	Public Property Description() As String
		Get
			Return Me._Description
		End Get
		Set
			If (String.Equals(Me._Description, value) = false) Then
				Me.OnDescriptionChanging(value)
				Me.SendPropertyChanging
				Me._Description = value
				Me.SendPropertyChanged("Description")
				Me.OnDescriptionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MonitorTimeCapacity", DbType:="Bit")>  _
	Public Property MonitorTimeCapacity() As System.Nullable(Of Boolean)
		Get
			Return Me._MonitorTimeCapacity
		End Get
		Set
			If (Me._MonitorTimeCapacity.Equals(value) = false) Then
				Me.OnMonitorTimeCapacityChanging(value)
				Me.SendPropertyChanging
				Me._MonitorTimeCapacity = value
				Me.SendPropertyChanged("MonitorTimeCapacity")
				Me.OnMonitorTimeCapacityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MonthlyTargetTimeCapacity", DbType:="Int")>  _
	Public Property MonthlyTargetTimeCapacity() As System.Nullable(Of Integer)
		Get
			Return Me._MonthlyTargetTimeCapacity
		End Get
		Set
			If (Me._MonthlyTargetTimeCapacity.Equals(value) = false) Then
				Me.OnMonthlyTargetTimeCapacityChanging(value)
				Me.SendPropertyChanging
				Me._MonthlyTargetTimeCapacity = value
				Me.SendPropertyChanged("MonthlyTargetTimeCapacity")
				Me.OnMonthlyTargetTimeCapacityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MonitorStartdate", DbType:="DateTime")>  _
	Public Property MonitorStartdate() As System.Nullable(Of Date)
		Get
			Return Me._MonitorStartdate
		End Get
		Set
			If (Me._MonitorStartdate.Equals(value) = false) Then
				Me.OnMonitorStartdateChanging(value)
				Me.SendPropertyChanging
				Me._MonitorStartdate = value
				Me.SendPropertyChanged("MonitorStartdate")
				Me.OnMonitorStartdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MonitorEnddate", DbType:="DateTime")>  _
	Public Property MonitorEnddate() As System.Nullable(Of Date)
		Get
			Return Me._MonitorEnddate
		End Get
		Set
			If (Me._MonitorEnddate.Equals(value) = false) Then
				Me.OnMonitorEnddateChanging(value)
				Me.SendPropertyChanging
				Me._MonitorEnddate = value
				Me.SendPropertyChanged("MonitorEnddate")
				Me.OnMonitorEnddateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TotalTargetTimeCapacity", DbType:="Int")>  _
	Public Property TotalTargetTimeCapacity() As System.Nullable(Of Integer)
		Get
			Return Me._TotalTargetTimeCapacity
		End Get
		Set
			If (Me._TotalTargetTimeCapacity.Equals(value) = false) Then
				Me.OnTotalTargetTimeCapacityChanging(value)
				Me.SendPropertyChanging
				Me._TotalTargetTimeCapacity = value
				Me.SendPropertyChanged("TotalTargetTimeCapacity")
				Me.OnTotalTargetTimeCapacityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CollectProductionUnits", DbType:="Bit NOT NULL")>  _
	Public Property CollectProductionUnits() As Boolean
		Get
			Return Me._CollectProductionUnits
		End Get
		Set
			If ((Me._CollectProductionUnits = value)  _
						= false) Then
				Me.OnCollectProductionUnitsChanging(value)
				Me.SendPropertyChanging
				Me._CollectProductionUnits = value
				Me.SendPropertyChanged("CollectProductionUnits")
				Me.OnCollectProductionUnitsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CollectProductionUnitsDescription", DbType:="Bit NOT NULL")>  _
	Public Property CollectProductionUnitsDescription() As Boolean
		Get
			Return Me._CollectProductionUnitsDescription
		End Get
		Set
			If ((Me._CollectProductionUnitsDescription = value)  _
						= false) Then
				Me.OnCollectProductionUnitsDescriptionChanging(value)
				Me.SendPropertyChanging
				Me._CollectProductionUnitsDescription = value
				Me.SendPropertyChanged("CollectProductionUnitsDescription")
				Me.OnCollectProductionUnitsDescriptionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastEditDate", DbType:="DateTime NOT NULL")>  _
	Public Property LastEditDate() As Date
		Get
			Return Me._LastEditDate
		End Get
		Set
			If ((Me._LastEditDate = value)  _
						= false) Then
				Me.OnLastEditDateChanging(value)
				Me.SendPropertyChanging
				Me._LastEditDate = value
				Me.SendPropertyChanged("LastEditDate")
				Me.OnLastEditDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreationDate", DbType:="DateTime NOT NULL")>  _
	Public Property CreationDate() As Date
		Get
			Return Me._CreationDate
		End Get
		Set
			If ((Me._CreationDate = value)  _
						= false) Then
				Me.OnCreationDateChanging(value)
				Me.SendPropertyChanging
				Me._CreationDate = value
				Me.SendPropertyChanged("CreationDate")
				Me.OnCreationDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SyncGuid", DbType:="UniqueIdentifier NOT NULL")>  _
	Public Property SyncGuid() As System.Guid
		Get
			Return Me._SyncGuid
		End Get
		Set
			If ((Me._SyncGuid = value)  _
						= false) Then
				Me.OnSyncGuidChanging(value)
				Me.SendPropertyChanging
				Me._SyncGuid = value
				Me.SendPropertyChanged("SyncGuid")
				Me.OnSyncGuidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsDeleted", DbType:="Bit NOT NULL")>  _
	Public Property IsDeleted() As Boolean
		Get
			Return Me._IsDeleted
		End Get
		Set
			If ((Me._IsDeleted = value)  _
						= false) Then
				Me.OnIsDeletedChanging(value)
				Me.SendPropertyChanging
				Me._IsDeleted = value
				Me.SendPropertyChanged("IsDeleted")
				Me.OnIsDeletedChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
