'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Facesso.Functions.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte geben Sie den Vornamen ein!.
        '''</summary>
        Friend ReadOnly Property AddressDetails_FirstNameNullMessage() As String
            Get
                Return ResourceManager.GetString("AddressDetails_FirstNameNullMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte geben Sie den Nachnamen ein!.
        '''</summary>
        Friend ReadOnly Property AddressDetails_LastNameNullMessage() As String
            Get
                Return ResourceManager.GetString("AddressDetails_LastNameNullMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Lohntabelle zu bearbeiten!.
        '''</summary>
        Friend ReadOnly Property BonusListMaintenance_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("BonusListMaintenance_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Der eingegebene Wert hat nicht das richtige Format. Bitte korrigieren Sie die Eingabe!.
        '''</summary>
        Friend ReadOnly Property BonusListMaintenance_InputValueFormatError_MB_Body() As String
            Get
                Return ResourceManager.GetString("BonusListMaintenance_InputValueFormatError_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Falsches Eingabeformat:.
        '''</summary>
        Friend ReadOnly Property BonusListMaintenance_InputValueFormatError_MB_Title() As String
            Get
                Return ResourceManager.GetString("BonusListMaintenance_InputValueFormatError_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Die Kostenstelle mit der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte korrigieren Sie die Eingabe, und wählen Sie eine andere Kostenstellennr..
        '''</summary>
        Friend ReadOnly Property CostCenterInfoAdd_CostCenterNoAlreadyExist_MB_Body() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoAdd_CostCenterNoAlreadyExist_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kostenstellennr. schon vorhanden:.
        '''</summary>
        Friend ReadOnly Property CostCenterInfoAdd_CostCenterNoAlreadyExist_MB_Title() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoAdd_CostCenterNoAlreadyExist_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine neue Kostenstelle hinzuzufügen!.
        '''</summary>
        Friend ReadOnly Property CostCenterInfoAdd_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoAdd_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neue Kostenstelle anlegen.
        '''</summary>
        Friend ReadOnly Property CostCenterInfoAdd_FormCaption() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoAdd_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kostenstelle.
        '''</summary>
        Friend ReadOnly Property CostCenterInfoCenter_LocalizedTypeName() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoCenter_LocalizedTypeName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte wählen Sie zunächst eine Kostenstelle aus, bevor Sie die Funktion verwenden!.
        '''</summary>
        Friend ReadOnly Property CostCenterInfoCenter_NoSelectedCostCenter_MB_Body() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoCenter_NoSelectedCostCenter_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keine Kostenstelle ausgewählt!.
        '''</summary>
        Friend ReadOnly Property CostCenterInfoCenter_NoSelectedCostCenter_MB_Title() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoCenter_NoSelectedCostCenter_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Liste der Kostenstellen einzusehen!.
        '''</summary>
        Friend ReadOnly Property CostCenterInfoCollectionGet_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoCollectionGet_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine Kostenstelle zu löschen!.
        '''</summary>
        Friend ReadOnly Property CostCenterInfoDelete_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoDelete_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine Kostenstelle zu bearbeiten!.
        '''</summary>
        Friend ReadOnly Property CostCenterInfoEdit_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoEdit_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kostenstelle bearbeiten.
        '''</summary>
        Friend ReadOnly Property CostCenterInfoEdit_FormCaption() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoEdit_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kostenstellendetails ansehen.
        '''</summary>
        Friend ReadOnly Property CostCenterInfoView_FormCaption() As String
            Get
                Return ResourceManager.GetString("CostCenterInfoView_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben keine Kostenstelle ausgewählt. Bitte wählen Sie eine Kostenstelle aus..
        '''</summary>
        Friend ReadOnly Property CostCenterSelection_NoSelection_MB_Body() As String
            Get
                Return ResourceManager.GetString("CostCenterSelection_NoSelection_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keine Kostenstelle selektiert:.
        '''</summary>
        Friend ReadOnly Property CostCenterSelection_NoSelection_MB_Title() As String
            Get
                Return ResourceManager.GetString("CostCenterSelection_NoSelection_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen neuen Mitarbeiter hinzuzufügen!.
        '''</summary>
        Friend ReadOnly Property EmployeeInfoAdd_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoAdd_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neuen Mitarbeiter anlegen.
        '''</summary>
        Friend ReadOnly Property EmployeeInfoAdd_FormCaption() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoAdd_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Die Personalnummer mit der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte korrigieren Sie die Eingabe, und wählen Sie eine andere Personalnr..
        '''</summary>
        Friend ReadOnly Property EmployeeInfoAdd_PersonnelNoAlreadyExist_MB_Body() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoAdd_PersonnelNoAlreadyExist_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Personalnr. schon vorhanden:.
        '''</summary>
        Friend ReadOnly Property EmployeeInfoAdd_PersonnelNoAlreadyExist_MB_Title() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoAdd_PersonnelNoAlreadyExist_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Für {0} verwenden:.
        '''</summary>
        Friend ReadOnly Property EmployeeInfoAddEditView_Dialog_IncentiveSynonym() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoAddEditView_Dialog_IncentiveSynonym", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mitarbeiter.
        '''</summary>
        Friend ReadOnly Property EmployeeInfoCenter_LocalizedTypeName() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoCenter_LocalizedTypeName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte wählen Sie zunächst einen Mitarbeiter aus, bevor Sie die Funktion verwenden!.
        '''</summary>
        Friend ReadOnly Property EmployeeInfoCenter_NoSelectedEmployee_MB_Body() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoCenter_NoSelectedEmployee_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kein Mitarbeiter ausgewählt!.
        '''</summary>
        Friend ReadOnly Property EmployeeInfoCenter_NoSelectedEmployee_MB_Title() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoCenter_NoSelectedEmployee_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Liste der Mitarbeiter einzusehen!.
        '''</summary>
        Friend ReadOnly Property EmployeeInfoCollectionGet_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoCollectionGet_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen Mitarbeiter zu löschen!.
        '''</summary>
        Friend ReadOnly Property EmployeeInfoDelete_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoDelete_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um Daten eines Mitarbeiters zu bearbeiten!.
        '''</summary>
        Friend ReadOnly Property EmployeeInfoEdit_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoEdit_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mitarbeiter bearbeiten.
        '''</summary>
        Friend ReadOnly Property EmployeeInfoEdit_FormCaption() As String
            Get
                Return ResourceManager.GetString("EmployeeInfoEdit_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %.
        '''</summary>
        Friend ReadOnly Property Incentive_Dimension() As String
            Get
                Return ResourceManager.GetString("Incentive_Dimension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zeitgrad.
        '''</summary>
        Friend ReadOnly Property Incentive_Synonym() As String
            Get
                Return ResourceManager.GetString("Incentive_Synonym", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to €.
        '''</summary>
        Friend ReadOnly Property Incentive_WageCurrency() As String
            Get
                Return ResourceManager.GetString("Incentive_WageCurrency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prämienlohn.
        '''</summary>
        Friend ReadOnly Property Incentive_WageSynonym() As String
            Get
                Return ResourceManager.GetString("Incentive_WageSynonym", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine Prämienlohnberechnung durchzuführen!.
        '''</summary>
        Friend ReadOnly Property IncentiveWageCalculation_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("IncentiveWageCalculation_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Hinzufügen.
        '''</summary>
        Friend ReadOnly Property InfoItemBase_AddCommandButtonText() As String
            Get
                Return ResourceManager.GetString("InfoItemBase_AddCommandButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Über&amp;nehmen.
        '''</summary>
        Friend ReadOnly Property InfoItemBase_EditCommandButtonText() As String
            Get
                Return ResourceManager.GetString("InfoItemBase_EditCommandButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte überprüfen Sie folgende Eingabefelder auf unvollständige Eingaben:.
        '''</summary>
        Friend ReadOnly Property InfoItemBase_NullsInFields_MB_BodyPrefix() As String
            Get
                Return ResourceManager.GetString("InfoItemBase_NullsInFields_MB_BodyPrefix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eingabe überprüfen:.
        '''</summary>
        Friend ReadOnly Property InfoItemBase_NullsInFields_MB_Title() As String
            Get
                Return ResourceManager.GetString("InfoItemBase_NullsInFields_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend ReadOnly Property InfoItemBase_ViewCommandButtonText() As String
            Get
                Return ResourceManager.GetString("InfoItemBase_ViewCommandButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen neuen REFA-Arbeitswert hinzuzufügen!.
        '''</summary>
        Friend ReadOnly Property LabourValueInfoAdd_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoAdd_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neuen REFA-Arbeitswert anlegen.
        '''</summary>
        Friend ReadOnly Property LabourValueInfoAdd_FormCaption() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoAdd_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Der REFA-Arbeitswert mit dem der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte korrigieren Sie die Eingabe, und wählen Sie eine andere Bezeichnung..
        '''</summary>
        Friend ReadOnly Property LabourValueInfoAdd_NumberAlreadyExists_MB_Body() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoAdd_NumberAlreadyExists_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arbeitswert schon vorhanden:.
        '''</summary>
        Friend ReadOnly Property LabourValueInfoAdd_NumberAlreadyExists_MB_Title() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoAdd_NumberAlreadyExists_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arbeitswert.
        '''</summary>
        Friend ReadOnly Property LabourValueInfoCenter_LocalizedTypeName() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoCenter_LocalizedTypeName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte wählen Sie zunächst einen Arbeitswert aus, bevor Sie die Funktion verwenden!.
        '''</summary>
        Friend ReadOnly Property LabourValueInfoCenter_NoSelectedLabourValue_MB_Body() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoCenter_NoSelectedLabourValue_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kein Arbeitswert ausgewählt!.
        '''</summary>
        Friend ReadOnly Property LabourValueInfoCenter_NoSelectedLabourValue_MB_Title() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoCenter_NoSelectedLabourValue_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Liste der Arbeitswerte einzusehen!.
        '''</summary>
        Friend ReadOnly Property LabourValueInfoCollectionGet_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoCollectionGet_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen REFA-Arbeitswert zu löschen!.
        '''</summary>
        Friend ReadOnly Property LabourValueInfoDelete_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoDelete_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen Arbeitswert zu bearbeiten!.
        '''</summary>
        Friend ReadOnly Property LabourValueInfoEdit_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoEdit_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to REFA-Arbeitswert bearbeiten.
        '''</summary>
        Friend ReadOnly Property LabourValueInfoEdit_FormCaption() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoEdit_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to REFA-Arbeitswertdetails ansehen.
        '''</summary>
        Friend ReadOnly Property LabourValueInfoView_FormCaption() As String
            Get
                Return ResourceManager.GetString("LabourValueInfoView_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neue Kostenstelle anlegen.
        '''</summary>
        Friend ReadOnly Property SubsidiaryInfoAdd_FormCaption() As String
            Get
                Return ResourceManager.GetString("SubsidiaryInfoAdd_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Die Subsidiarität namens {0} existiert bereits. Bitte korrigieren Sie die Eingabe, und bestimmen Sie einen anderen Namen für die Subsidiarität..
        '''</summary>
        Friend ReadOnly Property SubsidiaryInfoAdd_SubsidiaryNameAlreadyExist_MB_Body() As String
            Get
                Return ResourceManager.GetString("SubsidiaryInfoAdd_SubsidiaryNameAlreadyExist_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kostenstellennr. schon vorhanden:.
        '''</summary>
        Friend ReadOnly Property SubsidiaryInfoAdd_SubsidiaryNameAlreadyExist_MB_Title() As String
            Get
                Return ResourceManager.GetString("SubsidiaryInfoAdd_SubsidiaryNameAlreadyExist_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nur Administratoren können neue Subsidiaritäten anlegen, vorhandene bearbeiten oder löschen.
        '''</summary>
        Friend ReadOnly Property SubsidiaryInfoAddEditDelete_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("SubsidiaryInfoAddEditDelete_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subsidiaritäten bearbeiten.
        '''</summary>
        Friend ReadOnly Property SubsidiaryInfoEdit_FormCaption() As String
            Get
                Return ResourceManager.GetString("SubsidiaryInfoEdit_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte wählen Sie zunächst eine Subsidiarität aus, bevor Sie die Funktion verwenden!.
        '''</summary>
        Friend ReadOnly Property SubsidiaryInfoManager_NoSelectedSubsidiary_MB_Body() As String
            Get
                Return ResourceManager.GetString("SubsidiaryInfoManager_NoSelectedSubsidiary_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keine Subsidiarität ausgewählt!.
        '''</summary>
        Friend ReadOnly Property SubsidiaryInfoManager_NoSelectedSubsidiary_MB_Title() As String
            Get
                Return ResourceManager.GetString("SubsidiaryInfoManager_NoSelectedSubsidiary_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen neuen Benutzer hinzuzufügen!.
        '''</summary>
        Friend ReadOnly Property UserInfoAdd_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("UserInfoAdd_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neuen Benutzer anlegen.
        '''</summary>
        Friend ReadOnly Property UserInfoAdd_FormCaption() As String
            Get
                Return ResourceManager.GetString("UserInfoAdd_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Der Benutzername mit der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte wählen Sie einen anderen Benutzernamen!.
        '''</summary>
        Friend ReadOnly Property UserInfoAdd_UsernameAlreadyExist_MB_Body() As String
            Get
                Return ResourceManager.GetString("UserInfoAdd_UsernameAlreadyExist_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Benutzername schon vorhanden:.
        '''</summary>
        Friend ReadOnly Property UserInfoAdd_UsernameAlreadyExist_MB_Title() As String
            Get
                Return ResourceManager.GetString("UserInfoAdd_UsernameAlreadyExist_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adressendetails für Benutzer erfassen:.
        '''</summary>
        Friend ReadOnly Property UserInfoAddOrEdit_AddressDetailsDialogTitle() As String
            Get
                Return ResourceManager.GetString("UserInfoAddOrEdit_AddressDetailsDialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben kein Passwort eingegeben. Facesso erlaubt es aus Sicherheitsgründen nicht, dass Benutzer ohne Passwort angelegt sind..
        '''</summary>
        Friend ReadOnly Property UserInfoAddOrEdit_NoPassword_MB_Body() As String
            Get
                Return ResourceManager.GetString("UserInfoAddOrEdit_NoPassword_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kein Passwort eingegeben:.
        '''</summary>
        Friend ReadOnly Property UserInfoAddOrEdit_NoPassword_MB_Title() As String
            Get
                Return ResourceManager.GetString("UserInfoAddOrEdit_NoPassword_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Die Passwort-Wiederholung stimmt nicht mit dem eingegebenen Passwort überein. Bitte führen Sie die Passworteingabe und die Passwortwiederholung als Bestätigung erneut durch..
        '''</summary>
        Friend ReadOnly Property UserInfoAddOrEdit_PasswordRepetitionFailed_MB_Body() As String
            Get
                Return ResourceManager.GetString("UserInfoAddOrEdit_PasswordRepetitionFailed_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passwörter stimmen nicht überein:.
        '''</summary>
        Friend ReadOnly Property UserInfoAddOrEdit_PasswordRepetitionFailed_MB_Title() As String
            Get
                Return ResourceManager.GetString("UserInfoAddOrEdit_PasswordRepetitionFailed_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Benutzer.
        '''</summary>
        Friend ReadOnly Property UserInfoCenter_LocalizedTypeName() As String
            Get
                Return ResourceManager.GetString("UserInfoCenter_LocalizedTypeName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte wählen Sie zunächst einen Benutzer aus, bevor Sie die Funktion verwenden!.
        '''</summary>
        Friend ReadOnly Property UserInfoCenter_NoSelectedUser_MB_Body() As String
            Get
                Return ResourceManager.GetString("UserInfoCenter_NoSelectedUser_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kein Benutzer ausgewählt:.
        '''</summary>
        Friend ReadOnly Property UserInfoCenter_NoSelectedUser_MB_Title() As String
            Get
                Return ResourceManager.GetString("UserInfoCenter_NoSelectedUser_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Liste der Benutzer einzusehen!.
        '''</summary>
        Friend ReadOnly Property UserInfoCollectionGet_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("UserInfoCollectionGet_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Daten eines Benutzers zu bearbeiten!.
        '''</summary>
        Friend ReadOnly Property UserInfoEdit_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("UserInfoEdit_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Benutzerdaten bearbeiten.
        '''</summary>
        Friend ReadOnly Property UserInfoEdit_FormCaption() As String
            Get
                Return ResourceManager.GetString("UserInfoEdit_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Benutzerdatendetails ansehen.
        '''</summary>
        Friend ReadOnly Property UserInfoView_FormCaption() As String
            Get
                Return ResourceManager.GetString("UserInfoView_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine neue Lohngruppe hinzuzufügen!.
        '''</summary>
        Friend ReadOnly Property WageGroupInfoAdd_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("WageGroupInfoAdd_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neue Lohngruppe anlegen.
        '''</summary>
        Friend ReadOnly Property WageGroupInfoAdd_FormCaption() As String
            Get
                Return ResourceManager.GetString("WageGroupInfoAdd_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Die Lohngruppe mit dem Kürzel/der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte korrigieren Sie die Eingabe, und wählen Sie eine andere Bezeichnung..
        '''</summary>
        Friend ReadOnly Property WageGroupInfoAdd_TokenAlreadyExists_MB_Body() As String
            Get
                Return ResourceManager.GetString("WageGroupInfoAdd_TokenAlreadyExists_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lohngruppe schon vorhanden:.
        '''</summary>
        Friend ReadOnly Property WageGroupInfoAdd_TokenAlreadyExists_MB_Title() As String
            Get
                Return ResourceManager.GetString("WageGroupInfoAdd_TokenAlreadyExists_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lohngruppe.
        '''</summary>
        Friend ReadOnly Property WageGroupInfoCenter_LocalizedTypeName() As String
            Get
                Return ResourceManager.GetString("WageGroupInfoCenter_LocalizedTypeName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte wählen Sie zunächst eine Lohngruppe aus, bevor Sie die Funktion verwenden!.
        '''</summary>
        Friend ReadOnly Property WageGroupInfoCenter_NoSelectedWageGroup_MB_Body() As String
            Get
                Return ResourceManager.GetString("WageGroupInfoCenter_NoSelectedWageGroup_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keine Lohngruppe ausgewählt!.
        '''</summary>
        Friend ReadOnly Property WageGroupInfoCenter_NoSelectedWageGroup_MB_Title() As String
            Get
                Return ResourceManager.GetString("WageGroupInfoCenter_NoSelectedWageGroup_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Liste der Lohngruppen einzusehen!.
        '''</summary>
        Friend ReadOnly Property WageGroupInfoCollectionGet_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("WageGroupInfoCollectionGet_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine Lohngruppe zu bearbeiten!.
        '''</summary>
        Friend ReadOnly Property WageGroupInfoEdit_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("WageGroupInfoEdit_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lohngruppendaten bearbeiten.
        '''</summary>
        Friend ReadOnly Property WageGroupInfoEdit_FormCaption() As String
            Get
                Return ResourceManager.GetString("WageGroupInfoEdit_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lohngruppendetails ansehen.
        '''</summary>
        Friend ReadOnly Property WageGroupInfoView_FormCaption() As String
            Get
                Return ResourceManager.GetString("WageGroupInfoView_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie besitzen nicht die erforderlichen Rechte, um eine Produktiv-Site-Analyse durchzuführen!.
        '''</summary>
        Friend ReadOnly Property WorkGroupAnalysis_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("WorkGroupAnalysis_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine neue Produktiv-Site anzulegen!.
        '''</summary>
        Friend ReadOnly Property WorkGroupInfoAdd_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("WorkGroupInfoAdd_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neue Produktiv-Site einrichten.
        '''</summary>
        Friend ReadOnly Property WorkGroupInfoAdd_FormCaption() As String
            Get
                Return ResourceManager.GetString("WorkGroupInfoAdd_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Die Produktiv-Site mit der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte korrigieren Sie die Eingabe, und wählen Sie eine andere Nummer..
        '''</summary>
        Friend ReadOnly Property WorkGroupInfoAdd_WorkGroupNumberAlreadyExists_MB_Body() As String
            Get
                Return ResourceManager.GetString("WorkGroupInfoAdd_WorkGroupNumberAlreadyExists_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Produktiv-Site schon vorhanden:.
        '''</summary>
        Friend ReadOnly Property WorkGroupInfoAdd_WorkGroupNumberAlreadyExists_MB_Title() As String
            Get
                Return ResourceManager.GetString("WorkGroupInfoAdd_WorkGroupNumberAlreadyExists_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Produktiv-Site.
        '''</summary>
        Friend ReadOnly Property WorkGroupInfoCenter_LocalizedTypeName() As String
            Get
                Return ResourceManager.GetString("WorkGroupInfoCenter_LocalizedTypeName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte wählen Sie zunächst eine Produktiv-Site aus, bevor Sie die Funktion verwenden!.
        '''</summary>
        Friend ReadOnly Property WorkGroupInfoCenter_NoSelectedWorkGroup_MB_Body() As String
            Get
                Return ResourceManager.GetString("WorkGroupInfoCenter_NoSelectedWorkGroup_MB_Body", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keine Produktiv-Site ausgewählt!.
        '''</summary>
        Friend ReadOnly Property WorkGroupInfoCenter_NoSelectedWorkGroup_MB_Title() As String
            Get
                Return ResourceManager.GetString("WorkGroupInfoCenter_NoSelectedWorkGroup_MB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine Produktiv-Site zu löschen!.
        '''</summary>
        Friend ReadOnly Property WorkGroupInfoDelete_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("WorkGroupInfoDelete_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Stammdaten einer Produktiv-Site zu bearbeiten!.
        '''</summary>
        Friend ReadOnly Property WorkGroupInfoEdit_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("WorkGroupInfoEdit_DeniedDueToRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Produktiv-Site-Stammdaten bearbeiten.
        '''</summary>
        Friend ReadOnly Property WorkGroupInfoEdit_FormCaption() As String
            Get
                Return ResourceManager.GetString("WorkGroupInfoEdit_FormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um den Produktiv-Site-Manager zu verwenden!.
        '''</summary>
        Friend ReadOnly Property WorkGroupManager_DeniedDueToRole() As String
            Get
                Return ResourceManager.GetString("WorkGroupManager_DeniedDueToRole", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
