// <auto-generated>
//     This code was generated from the VB Resources.Designer.vb.
// </auto-generated>

using System;
using System.Globalization;
using System.Resources;

namespace Facesso.Data.My.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal static class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                    resourceMan = new ResourceManager("Facesso.Data.Resources", typeof(Resources).Assembly);
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string CostCenterInfo_ColumnCaption_Description
        {
            get { return ResourceManager.GetString("CostCenterInfo_ColumnCaption_Description", resourceCulture); }
        }

        internal static string CostCenterInfo_ColumnCaption_Name
        {
            get { return ResourceManager.GetString("CostCenterInfo_ColumnCaption_Name", resourceCulture); }
        }

        internal static string CostCenterInfo_ColumnCaption_No
        {
            get { return ResourceManager.GetString("CostCenterInfo_ColumnCaption_No", resourceCulture); }
        }

        internal static string SELECT_ProductionDataAmount
        {
            get { return ResourceManager.GetString("SELECT_ProductionDataAmount", resourceCulture); }
        }

        internal static string Sp_Main_FailedInstancingDueToLicence
        {
            get { return ResourceManager.GetString("Sp_Main_FailedInstancingDueToLicence", resourceCulture); }
        }

        internal static string Sp_Main_OpenFacessoConnectionFailed
        {
            get { return ResourceManager.GetString("Sp_Main_OpenFacessoConnectionFailed", resourceCulture); }
        }
    }
}
