// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using System.Drawing;

namespace ActiveDev.Data.SqlClient.My
{
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager _resourceMan;
        private static System.Globalization.CultureInfo _resourceCulture;

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (_resourceMan == null)
                    _resourceMan = new System.Resources.ResourceManager("ActiveDev.Data.SqlClient.Resources", typeof(Resources).Assembly);
                return _resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static Bitmap document => (Bitmap)ResourceManager.GetObject("document", _resourceCulture);

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static Bitmap drive => (Bitmap)ResourceManager.GetObject("drive", _resourceCulture);

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static Bitmap VSFolder_closed => (Bitmap)ResourceManager.GetObject("VSFolder_closed", _resourceCulture);
    }
}
