'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Facesso.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CompLogo_V2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CompLogo_V2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gewiesen..
        '''</summary>
        Friend ReadOnly Property CostCenter_Base_Description() As String
            Get
                Return ResourceManager.GetString("CostCenter_Base_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Systemkostenstelle.
        '''</summary>
        Friend ReadOnly Property CostCenter_Base_Name() As String
            Get
                Return ResourceManager.GetString("CostCenter_Base_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hinzufügen.
        '''</summary>
        Friend ReadOnly Property Dialog_InfoItemAddEditView_OKAdd() As String
            Get
                Return ResourceManager.GetString("Dialog_InfoItemAddEditView_OKAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Übernehmen.
        '''</summary>
        Friend ReadOnly Property Dialog_InfoItemAddEditView_OKEdit() As String
            Get
                Return ResourceManager.GetString("Dialog_InfoItemAddEditView_OKEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Keyboard_Check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Keyboard Check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Keyboard_Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Keyboard Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keine Rechte|Produktionauswertungen einsehen|Mitarbeiterauswertungen einsehen|Systemdaten einsehen|Produktionsauswertungen drucken|Mitarbeiterauswertungen drucken|Systemdaten drucken|Neue Produktionsdaten erfassen|Neue Mitarbeiterdaten erfassen|Produktionsdaten korrigieren|Mitarbeiterdaten korrigieren|Lohnabrechnungen durchführen|Import-Funktionen durchführen|Export-Funktionen durchführen|Import-/Export-Regeln ändern|Stammdaten ändern|Systemdaten ändern|Systempflege durchführen|Administrator-Rechte.
        '''</summary>
        Friend ReadOnly Property RolesList() As String
            Get
                Return ResourceManager.GetString("RolesList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Niederlassung.
        '''</summary>
        Friend ReadOnly Property SubsidiaryDefaultSynonym() As String
            Get
                Return ResourceManager.GetString("SubsidiaryDefaultSynonym", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Das Konto mit dem angegebenen Benutzername ist in der Benutzerdatenbank nicht vorhanden!.
        '''</summary>
        Friend ReadOnly Property UserInfo_UserNotExisting() As String
            Get
                Return ResourceManager.GetString("UserInfo_UserNotExisting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Das eingegebene Kennwort für diesen Benutzer stimmt nicht mit dem hinterlegten Kennwort überein!.
        '''</summary>
        Friend ReadOnly Property UserInfo_WrongPassword() As String
            Get
                Return ResourceManager.GetString("UserInfo_WrongPassword", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
