// <auto-generated>
//     This code was generated from the VB Resources.Designer.vb.
// </auto-generated>

using System;
using System.Globalization;
using System.Resources;

namespace Facesso.My.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal static class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                    resourceMan = new ResourceManager("Facesso.Resources", typeof(Resources).Assembly);
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static System.Drawing.Bitmap CompLogo_V2
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("CompLogo_V2", resourceCulture); }
        }

        internal static string CostCenter_Base_Description
        {
            get { return ResourceManager.GetString("CostCenter_Base_Description", resourceCulture); }
        }

        internal static string CostCenter_Base_Name
        {
            get { return ResourceManager.GetString("CostCenter_Base_Name", resourceCulture); }
        }

        internal static string Dialog_InfoItemAddEditView_OKAdd
        {
            get { return ResourceManager.GetString("Dialog_InfoItemAddEditView_OKAdd", resourceCulture); }
        }

        internal static string Dialog_InfoItemAddEditView_OKEdit
        {
            get { return ResourceManager.GetString("Dialog_InfoItemAddEditView_OKEdit", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Keyboard_Check
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Keyboard Check", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Keyboard_Error
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Keyboard Error", resourceCulture); }
        }

        internal static string RolesList
        {
            get { return ResourceManager.GetString("RolesList", resourceCulture); }
        }

        internal static string SubsidiaryDefaultSynonym
        {
            get { return ResourceManager.GetString("SubsidiaryDefaultSynonym", resourceCulture); }
        }

        internal static string UserInfo_UserNotExisting
        {
            get { return ResourceManager.GetString("UserInfo_UserNotExisting", resourceCulture); }
        }

        internal static string UserInfo_WrongPassword
        {
            get { return ResourceManager.GetString("UserInfo_WrongPassword", resourceCulture); }
        }
    }
}
