// <auto-generated>
//     This code was generated from the VB Settings.Designer.vb.
// </auto-generated>

using System.Configuration;
using System.ComponentModel;

namespace Facesso.My
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    [global::System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal sealed partial class Settings : ApplicationSettingsBase
    {
        private static Settings defaultInstance = (Settings)Synchronized(new Settings());

        public static Settings Default => defaultInstance;
    }
}
