using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace Facesso.Functions.My
{
    //This class was auto-generated by the StronglyTypedResourceBuilder
    //class via a tool like ResGen or Visual Studio.
    //To add or remove a member, edit your .ResX file then rerun ResGen
    //with the /str option, or rebuild your VS project.
    /// <summary>
    ///  A strongly-typed resource class, for looking up localized strings, etc.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualBasic.HideModuleNameAttribute()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;
        /// <summary>
        ///  Returns the cached ResourceManager instance used by this class.
        ///</summary>
        [System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Facesso.Functions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///  Overrides the current thread's CurrentUICulture property for all
        ///  resource lookups using this strongly typed resource class.
        ///</summary>
        [System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Bitte geben Sie den Vornamen ein!.
        ///</summary>
        internal static string AddressDetails_FirstNameNullMessage
        {
            get
            {
                return ResourceManager.GetString("AddressDetails_FirstNameNullMessage", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Bitte geben Sie den Nachnamen ein!.
        ///</summary>
        internal static string AddressDetails_LastNameNullMessage
        {
            get
            {
                return ResourceManager.GetString("AddressDetails_LastNameNullMessage", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Lohntabelle zu bearbeiten!.
        ///</summary>
        internal static string BonusListMaintenance_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("BonusListMaintenance_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Der eingegebene Wert hat nicht das richtige Format. Bitte korrigieren Sie die Eingabe!.
        ///</summary>
        internal static string BonusListMaintenance_InputValueFormatError_MB_Body
        {
            get
            {
                return ResourceManager.GetString("BonusListMaintenance_InputValueFormatError_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Falsches Eingabeformat:.
        ///</summary>
        internal static string BonusListMaintenance_InputValueFormatError_MB_Title
        {
            get
            {
                return ResourceManager.GetString("BonusListMaintenance_InputValueFormatError_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Die Kostenstelle mit der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte korrigieren Sie die Eingabe, und wählen Sie eine andere Kostenstellennr..
        ///</summary>
        internal static string CostCenterInfoAdd_CostCenterNoAlreadyExist_MB_Body
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoAdd_CostCenterNoAlreadyExist_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Kostenstellennr. schon vorhanden:.
        ///</summary>
        internal static string CostCenterInfoAdd_CostCenterNoAlreadyExist_MB_Title
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoAdd_CostCenterNoAlreadyExist_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine neue Kostenstelle hinzuzufügen!.
        ///</summary>
        internal static string CostCenterInfoAdd_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoAdd_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Neue Kostenstelle anlegen.
        ///</summary>
        internal static string CostCenterInfoAdd_FormCaption
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoAdd_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Kostenstelle.
        ///</summary>
        internal static string CostCenterInfoCenter_LocalizedTypeName
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoCenter_LocalizedTypeName", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Bitte wählen Sie zunächst eine Kostenstelle aus, bevor Sie die Funktion verwenden!.
        ///</summary>
        internal static string CostCenterInfoCenter_NoSelectedCostCenter_MB_Body
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoCenter_NoSelectedCostCenter_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Keine Kostenstelle ausgewählt!.
        ///</summary>
        internal static string CostCenterInfoCenter_NoSelectedCostCenter_MB_Title
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoCenter_NoSelectedCostCenter_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Liste der Kostenstellen einzusehen!.
        ///</summary>
        internal static string CostCenterInfoCollectionGet_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoCollectionGet_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine Kostenstelle zu löschen!.
        ///</summary>
        internal static string CostCenterInfoDelete_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoDelete_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine Kostenstelle zu bearbeiten!.
        ///</summary>
        internal static string CostCenterInfoEdit_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoEdit_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Kostenstelle bearbeiten.
        ///</summary>
        internal static string CostCenterInfoEdit_FormCaption
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoEdit_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Kostenstellendetails ansehen.
        ///</summary>
        internal static string CostCenterInfoView_FormCaption
        {
            get
            {
                return ResourceManager.GetString("CostCenterInfoView_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben keine Kostenstelle ausgewählt. Bitte wählen Sie eine Kostenstelle aus..
        ///</summary>
        internal static string CostCenterSelection_NoSelection_MB_Body
        {
            get
            {
                return ResourceManager.GetString("CostCenterSelection_NoSelection_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Keine Kostenstelle selektiert:.
        ///</summary>
        internal static string CostCenterSelection_NoSelection_MB_Title
        {
            get
            {
                return ResourceManager.GetString("CostCenterSelection_NoSelection_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen neuen Mitarbeiter hinzuzufügen!.
        ///</summary>
        internal static string EmployeeInfoAdd_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoAdd_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Neuen Mitarbeiter anlegen.
        ///</summary>
        internal static string EmployeeInfoAdd_FormCaption
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoAdd_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Die Personalnummer mit der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte korrigieren Sie die Eingabe, und wählen Sie eine andere Personalnr..
        ///</summary>
        internal static string EmployeeInfoAdd_PersonnelNoAlreadyExist_MB_Body
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoAdd_PersonnelNoAlreadyExist_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Personalnr. schon vorhanden:.
        ///</summary>
        internal static string EmployeeInfoAdd_PersonnelNoAlreadyExist_MB_Title
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoAdd_PersonnelNoAlreadyExist_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Für {0} verwenden:.
        ///</summary>
        internal static string EmployeeInfoAddEditView_Dialog_IncentiveSynonym
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoAddEditView_Dialog_IncentiveSynonym", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Mitarbeiter.
        ///</summary>
        internal static string EmployeeInfoCenter_LocalizedTypeName
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoCenter_LocalizedTypeName", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Bitte wählen Sie zunächst einen Mitarbeiter aus, bevor Sie die Funktion verwenden!.
        ///</summary>
        internal static string EmployeeInfoCenter_NoSelectedEmployee_MB_Body
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoCenter_NoSelectedEmployee_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Kein Mitarbeiter ausgewählt!.
        ///</summary>
        internal static string EmployeeInfoCenter_NoSelectedEmployee_MB_Title
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoCenter_NoSelectedEmployee_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Liste der Mitarbeiter einzusehen!.
        ///</summary>
        internal static string EmployeeInfoCollectionGet_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoCollectionGet_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen Mitarbeiter zu löschen!.
        ///</summary>
        internal static string EmployeeInfoDelete_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoDelete_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um Daten eines Mitarbeiters zu bearbeiten!.
        ///</summary>
        internal static string EmployeeInfoEdit_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoEdit_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Mitarbeiter bearbeiten.
        ///</summary>
        internal static string EmployeeInfoEdit_FormCaption
        {
            get
            {
                return ResourceManager.GetString("EmployeeInfoEdit_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to %.
        ///</summary>
        internal static string Incentive_Dimension
        {
            get
            {
                return ResourceManager.GetString("Incentive_Dimension", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Zeitgrad.
        ///</summary>
        internal static string Incentive_Synonym
        {
            get
            {
                return ResourceManager.GetString("Incentive_Synonym", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to €.
        ///</summary>
        internal static string Incentive_WageCurrency
        {
            get
            {
                return ResourceManager.GetString("Incentive_WageCurrency", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Prämienlohn.
        ///</summary>
        internal static string Incentive_WageSynonym
        {
            get
            {
                return ResourceManager.GetString("Incentive_WageSynonym", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine Prämienlohnberechnung durchzuführen!.
        ///</summary>
        internal static string IncentiveWageCalculation_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("IncentiveWageCalculation_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to &amp;Hinzufügen.
        ///</summary>
        internal static string InfoItemBase_AddCommandButtonText
        {
            get
            {
                return ResourceManager.GetString("InfoItemBase_AddCommandButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Über&amp;nehmen.
        ///</summary>
        internal static string InfoItemBase_EditCommandButtonText
        {
            get
            {
                return ResourceManager.GetString("InfoItemBase_EditCommandButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Bitte überprüfen Sie folgende Eingabefelder auf unvollständige Eingaben:.
        ///</summary>
        internal static string InfoItemBase_NullsInFields_MB_BodyPrefix
        {
            get
            {
                return ResourceManager.GetString("InfoItemBase_NullsInFields_MB_BodyPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Eingabe überprüfen:.
        ///</summary>
        internal static string InfoItemBase_NullsInFields_MB_Title
        {
            get
            {
                return ResourceManager.GetString("InfoItemBase_NullsInFields_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to &amp;OK.
        ///</summary>
        internal static string InfoItemBase_ViewCommandButtonText
        {
            get
            {
                return ResourceManager.GetString("InfoItemBase_ViewCommandButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen neuen REFA-Arbeitswert hinzuzufügen!.
        ///</summary>
        internal static string LabourValueInfoAdd_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoAdd_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Neuen REFA-Arbeitswert anlegen.
        ///</summary>
        internal static string LabourValueInfoAdd_FormCaption
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoAdd_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Der REFA-Arbeitswert mit dem der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte korrigieren Sie die Eingabe, und wählen Sie eine andere Bezeichnung..
        ///</summary>
        internal static string LabourValueInfoAdd_NumberAlreadyExists_MB_Body
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoAdd_NumberAlreadyExists_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Arbeitswert schon vorhanden:.
        ///</summary>
        internal static string LabourValueInfoAdd_NumberAlreadyExists_MB_Title
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoAdd_NumberAlreadyExists_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Arbeitswert.
        ///</summary>
        internal static string LabourValueInfoCenter_LocalizedTypeName
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoCenter_LocalizedTypeName", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Bitte wählen Sie zunächst einen Arbeitswert aus, bevor Sie die Funktion verwenden!.
        ///</summary>
        internal static string LabourValueInfoCenter_NoSelectedLabourValue_MB_Body
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoCenter_NoSelectedLabourValue_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Kein Arbeitswert ausgewählt!.
        ///</summary>
        internal static string LabourValueInfoCenter_NoSelectedLabourValue_MB_Title
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoCenter_NoSelectedLabourValue_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Liste der Arbeitswerte einzusehen!.
        ///</summary>
        internal static string LabourValueInfoCollectionGet_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoCollectionGet_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen REFA-Arbeitswert zu löschen!.
        ///</summary>
        internal static string LabourValueInfoDelete_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoDelete_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen Arbeitswert zu bearbeiten!.
        ///</summary>
        internal static string LabourValueInfoEdit_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoEdit_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to REFA-Arbeitswert bearbeiten.
        ///</summary>
        internal static string LabourValueInfoEdit_FormCaption
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoEdit_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to REFA-Arbeitswertdetails ansehen.
        ///</summary>
        internal static string LabourValueInfoView_FormCaption
        {
            get
            {
                return ResourceManager.GetString("LabourValueInfoView_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Neue Kostenstelle anlegen.
        ///</summary>
        internal static string SubsidiaryInfoAdd_FormCaption
        {
            get
            {
                return ResourceManager.GetString("SubsidiaryInfoAdd_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Die Subsidiarität namens {0} existiert bereits. Bitte korrigieren Sie die Eingabe, und bestimmen Sie einen anderen Namen für die Subsidiarität..
        ///</summary>
        internal static string SubsidiaryInfoAdd_SubsidiaryNameAlreadyExist_MB_Body
        {
            get
            {
                return ResourceManager.GetString("SubsidiaryInfoAdd_SubsidiaryNameAlreadyExist_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Kostenstellennr. schon vorhanden:.
        ///</summary>
        internal static string SubsidiaryInfoAdd_SubsidiaryNameAlreadyExist_MB_Title
        {
            get
            {
                return ResourceManager.GetString("SubsidiaryInfoAdd_SubsidiaryNameAlreadyExist_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Nur Administratoren können neue Subsidiaritäten anlegen, vorhandene bearbeiten oder löschen.
        ///</summary>
        internal static string SubsidiaryInfoAddEditDelete_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("SubsidiaryInfoAddEditDelete_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Subsidiaritäten bearbeiten.
        ///</summary>
        internal static string SubsidiaryInfoEdit_FormCaption
        {
            get
            {
                return ResourceManager.GetString("SubsidiaryInfoEdit_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Bitte wählen Sie zunächst eine Subsidiarität aus, bevor Sie die Funktion verwenden!.
        ///</summary>
        internal static string SubsidiaryInfoManager_NoSelectedSubsidiary_MB_Body
        {
            get
            {
                return ResourceManager.GetString("SubsidiaryInfoManager_NoSelectedSubsidiary_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Keine Subsidiarität ausgewählt!.
        ///</summary>
        internal static string SubsidiaryInfoManager_NoSelectedSubsidiary_MB_Title
        {
            get
            {
                return ResourceManager.GetString("SubsidiaryInfoManager_NoSelectedSubsidiary_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um einen neuen Benutzer hinzuzufügen!.
        ///</summary>
        internal static string UserInfoAdd_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("UserInfoAdd_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Neuen Benutzer anlegen.
        ///</summary>
        internal static string UserInfoAdd_FormCaption
        {
            get
            {
                return ResourceManager.GetString("UserInfoAdd_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Der Benutzername mit der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte wählen Sie einen anderen Benutzernamen!.
        ///</summary>
        internal static string UserInfoAdd_UsernameAlreadyExist_MB_Body
        {
            get
            {
                return ResourceManager.GetString("UserInfoAdd_UsernameAlreadyExist_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Benutzername schon vorhanden:.
        ///</summary>
        internal static string UserInfoAdd_UsernameAlreadyExist_MB_Title
        {
            get
            {
                return ResourceManager.GetString("UserInfoAdd_UsernameAlreadyExist_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Adressendetails für Benutzer erfassen:.
        ///</summary>
        internal static string UserInfoAddOrEdit_AddressDetailsDialogTitle
        {
            get
            {
                return ResourceManager.GetString("UserInfoAddOrEdit_AddressDetailsDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben kein Passwort eingegeben. Facesso erlaubt es aus Sicherheitsgründen nicht, dass Benutzer ohne Passwort angelegt sind..
        ///</summary>
        internal static string UserInfoAddOrEdit_NoPassword_MB_Body
        {
            get
            {
                return ResourceManager.GetString("UserInfoAddOrEdit_NoPassword_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Kein Passwort eingegeben:.
        ///</summary>
        internal static string UserInfoAddOrEdit_NoPassword_MB_Title
        {
            get
            {
                return ResourceManager.GetString("UserInfoAddOrEdit_NoPassword_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Die Passwort-Wiederholung stimmt nicht mit dem eingegebenen Passwort überein. Bitte führen Sie die Passworteingabe und die Passwortwiederholung als Bestätigung erneut durch..
        ///</summary>
        internal static string UserInfoAddOrEdit_PasswordRepetitionFailed_MB_Body
        {
            get
            {
                return ResourceManager.GetString("UserInfoAddOrEdit_PasswordRepetitionFailed_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Passwörter stimmen nicht überein:.
        ///</summary>
        internal static string UserInfoAddOrEdit_PasswordRepetitionFailed_MB_Title
        {
            get
            {
                return ResourceManager.GetString("UserInfoAddOrEdit_PasswordRepetitionFailed_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Benutzer.
        ///</summary>
        internal static string UserInfoCenter_LocalizedTypeName
        {
            get
            {
                return ResourceManager.GetString("UserInfoCenter_LocalizedTypeName", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Bitte wählen Sie zunächst einen Benutzer aus, bevor Sie die Funktion verwenden!.
        ///</summary>
        internal static string UserInfoCenter_NoSelectedUser_MB_Body
        {
            get
            {
                return ResourceManager.GetString("UserInfoCenter_NoSelectedUser_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Kein Benutzer ausgewählt:.
        ///</summary>
        internal static string UserInfoCenter_NoSelectedUser_MB_Title
        {
            get
            {
                return ResourceManager.GetString("UserInfoCenter_NoSelectedUser_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Liste der Benutzer einzusehen!.
        ///</summary>
        internal static string UserInfoCollectionGet_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("UserInfoCollectionGet_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Daten eines Benutzers zu bearbeiten!.
        ///</summary>
        internal static string UserInfoEdit_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("UserInfoEdit_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Benutzerdaten bearbeiten.
        ///</summary>
        internal static string UserInfoEdit_FormCaption
        {
            get
            {
                return ResourceManager.GetString("UserInfoEdit_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Benutzerdatendetails ansehen.
        ///</summary>
        internal static string UserInfoView_FormCaption
        {
            get
            {
                return ResourceManager.GetString("UserInfoView_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine neue Lohngruppe hinzuzufügen!.
        ///</summary>
        internal static string WageGroupInfoAdd_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("WageGroupInfoAdd_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Neue Lohngruppe anlegen.
        ///</summary>
        internal static string WageGroupInfoAdd_FormCaption
        {
            get
            {
                return ResourceManager.GetString("WageGroupInfoAdd_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Die Lohngruppe mit dem Kürzel/der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte korrigieren Sie die Eingabe, und wählen Sie eine andere Bezeichnung..
        ///</summary>
        internal static string WageGroupInfoAdd_TokenAlreadyExists_MB_Body
        {
            get
            {
                return ResourceManager.GetString("WageGroupInfoAdd_TokenAlreadyExists_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Lohngruppe schon vorhanden:.
        ///</summary>
        internal static string WageGroupInfoAdd_TokenAlreadyExists_MB_Title
        {
            get
            {
                return ResourceManager.GetString("WageGroupInfoAdd_TokenAlreadyExists_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Lohngruppe.
        ///</summary>
        internal static string WageGroupInfoCenter_LocalizedTypeName
        {
            get
            {
                return ResourceManager.GetString("WageGroupInfoCenter_LocalizedTypeName", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Bitte wählen Sie zunächst eine Lohngruppe aus, bevor Sie die Funktion verwenden!.
        ///</summary>
        internal static string WageGroupInfoCenter_NoSelectedWageGroup_MB_Body
        {
            get
            {
                return ResourceManager.GetString("WageGroupInfoCenter_NoSelectedWageGroup_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Keine Lohngruppe ausgewählt!.
        ///</summary>
        internal static string WageGroupInfoCenter_NoSelectedWageGroup_MB_Title
        {
            get
            {
                return ResourceManager.GetString("WageGroupInfoCenter_NoSelectedWageGroup_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Liste der Lohngruppen einzusehen!.
        ///</summary>
        internal static string WageGroupInfoCollectionGet_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("WageGroupInfoCollectionGet_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine Lohngruppe zu bearbeiten!.
        ///</summary>
        internal static string WageGroupInfoEdit_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("WageGroupInfoEdit_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Lohngruppendaten bearbeiten.
        ///</summary>
        internal static string WageGroupInfoEdit_FormCaption
        {
            get
            {
                return ResourceManager.GetString("WageGroupInfoEdit_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Lohngruppendetails ansehen.
        ///</summary>
        internal static string WageGroupInfoView_FormCaption
        {
            get
            {
                return ResourceManager.GetString("WageGroupInfoView_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie besitzen nicht die erforderlichen Rechte, um eine Produktiv-Site-Analyse durchzuführen!.
        ///</summary>
        internal static string WorkGroupAnalysis_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("WorkGroupAnalysis_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine neue Produktiv-Site anzulegen!.
        ///</summary>
        internal static string WorkGroupInfoAdd_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("WorkGroupInfoAdd_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Neue Produktiv-Site einrichten.
        ///</summary>
        internal static string WorkGroupInfoAdd_FormCaption
        {
            get
            {
                return ResourceManager.GetString("WorkGroupInfoAdd_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Die Produktiv-Site mit der Nummer {0} existiert bereits in {1} &quot;{2}&quot;. Bitte korrigieren Sie die Eingabe, und wählen Sie eine andere Nummer..
        ///</summary>
        internal static string WorkGroupInfoAdd_WorkGroupNumberAlreadyExists_MB_Body
        {
            get
            {
                return ResourceManager.GetString("WorkGroupInfoAdd_WorkGroupNumberAlreadyExists_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Produktiv-Site schon vorhanden:.
        ///</summary>
        internal static string WorkGroupInfoAdd_WorkGroupNumberAlreadyExists_MB_Title
        {
            get
            {
                return ResourceManager.GetString("WorkGroupInfoAdd_WorkGroupNumberAlreadyExists_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Produktiv-Site.
        ///</summary>
        internal static string WorkGroupInfoCenter_LocalizedTypeName
        {
            get
            {
                return ResourceManager.GetString("WorkGroupInfoCenter_LocalizedTypeName", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Bitte wählen Sie zunächst eine Produktiv-Site aus, bevor Sie die Funktion verwenden!.
        ///</summary>
        internal static string WorkGroupInfoCenter_NoSelectedWorkGroup_MB_Body
        {
            get
            {
                return ResourceManager.GetString("WorkGroupInfoCenter_NoSelectedWorkGroup_MB_Body", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Keine Produktiv-Site ausgewählt!.
        ///</summary>
        internal static string WorkGroupInfoCenter_NoSelectedWorkGroup_MB_Title
        {
            get
            {
                return ResourceManager.GetString("WorkGroupInfoCenter_NoSelectedWorkGroup_MB_Title", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um eine Produktiv-Site zu löschen!.
        ///</summary>
        internal static string WorkGroupInfoDelete_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("WorkGroupInfoDelete_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um die Stammdaten einer Produktiv-Site zu bearbeiten!.
        ///</summary>
        internal static string WorkGroupInfoEdit_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("WorkGroupInfoEdit_DeniedDueToRole", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Produktiv-Site-Stammdaten bearbeiten.
        ///</summary>
        internal static string WorkGroupInfoEdit_FormCaption
        {
            get
            {
                return ResourceManager.GetString("WorkGroupInfoEdit_FormCaption", resourceCulture);
            }
        }

        /// <summary>
        ///  Looks up a localized string similar to Sie haben nicht die erforderlichen Rechte, um den Produktiv-Site-Manager zu verwenden!.
        ///</summary>
        internal static string WorkGroupManager_DeniedDueToRole
        {
            get
            {
                return ResourceManager.GetString("WorkGroupManager_DeniedDueToRole", resourceCulture);
            }
        }
    }
}