'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="MISDB")>  _
Partial Public Class KannegiesserDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.Facesso.Interfaces.My.MySettings.Default.MISDBConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="PROGHIST.GetMachines")>  _
	Public Function GetMachines() As ISingleResult(Of GetMachinesResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of GetMachinesResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="PROGHIST.GetProgHist")>  _
	Public Function GetProgHist(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="MachineID", DbType:="Int")> ByVal machineID As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ID", DbType:="Int")> ByVal iD As System.Nullable(Of Integer)) As ISingleResult(Of GetProgHistResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), machineID, iD)
		Return CType(result.ReturnValue,ISingleResult(Of GetProgHistResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="PROGHIST.GetPrograms")>  _
	Public Function GetPrograms() As ISingleResult(Of GetProgramsResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of GetProgramsResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="PROGHIST.GetArticles")>  _
	Public Function GetArticles() As ISingleResult(Of GetArticlesResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of GetArticlesResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="PROGHIST.GetArtHist")>  _
	Public Function GetArtHist(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="MachineID", DbType:="Int")> ByVal machineID As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="StartTime", DbType:="DateTime")> ByVal startTime As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="EndTime", DbType:="DateTime")> ByVal endTime As System.Nullable(Of Date)) As ISingleResult(Of GetArtHistResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), machineID, startTime, endTime)
		Return CType(result.ReturnValue,ISingleResult(Of GetArtHistResult))
	End Function
End Class

Partial Public Class GetMachinesResult
	
	Private _MachineID As Integer
	
	Private _MachineName As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MachineID", DbType:="Int NOT NULL")>  _
	Public Property MachineID() As Integer
		Get
			Return Me._MachineID
		End Get
		Set
			If ((Me._MachineID = value)  _
						= false) Then
				Me._MachineID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MachineName", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property MachineName() As String
		Get
			Return Me._MachineName
		End Get
		Set
			If (String.Equals(Me._MachineName, value) = false) Then
				Me._MachineName = value
			End If
		End Set
	End Property
End Class

Partial Public Class GetProgHistResult
	
	Private _ID As Long
	
	Private _DATUM As System.Nullable(Of Date)
	
	Private _TYP As System.Nullable(Of Integer)
	
	Private _ARTNR As System.Nullable(Of Integer)
	
	Private _STARTZEIT As System.Nullable(Of Date)
	
	Private _DAUER As System.Nullable(Of Double)
	
	Private _ZAEHLER As System.Nullable(Of Double)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", DbType:="BigInt NOT NULL")>  _
	Public Property ID() As Long
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me._ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DATUM", DbType:="DateTime")>  _
	Public Property DATUM() As System.Nullable(Of Date)
		Get
			Return Me._DATUM
		End Get
		Set
			If (Me._DATUM.Equals(value) = false) Then
				Me._DATUM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TYP", DbType:="Int")>  _
	Public Property TYP() As System.Nullable(Of Integer)
		Get
			Return Me._TYP
		End Get
		Set
			If (Me._TYP.Equals(value) = false) Then
				Me._TYP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ARTNR", DbType:="Int")>  _
	Public Property ARTNR() As System.Nullable(Of Integer)
		Get
			Return Me._ARTNR
		End Get
		Set
			If (Me._ARTNR.Equals(value) = false) Then
				Me._ARTNR = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STARTZEIT", DbType:="DateTime")>  _
	Public Property STARTZEIT() As System.Nullable(Of Date)
		Get
			Return Me._STARTZEIT
		End Get
		Set
			If (Me._STARTZEIT.Equals(value) = false) Then
				Me._STARTZEIT = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DAUER", DbType:="Float")>  _
	Public Property DAUER() As System.Nullable(Of Double)
		Get
			Return Me._DAUER
		End Get
		Set
			If (Me._DAUER.Equals(value) = false) Then
				Me._DAUER = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ZAEHLER", DbType:="Float")>  _
	Public Property ZAEHLER() As System.Nullable(Of Double)
		Get
			Return Me._ZAEHLER
		End Get
		Set
			If (Me._ZAEHLER.Equals(value) = false) Then
				Me._ZAEHLER = value
			End If
		End Set
	End Property
End Class

Partial Public Class GetProgramsResult
	
	Private _MachineID As Integer
	
	Private _ProgramID As Short
	
	Private _ProgramName As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MachineID", DbType:="Int NOT NULL")>  _
	Public Property MachineID() As Integer
		Get
			Return Me._MachineID
		End Get
		Set
			If ((Me._MachineID = value)  _
						= false) Then
				Me._MachineID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProgramID", DbType:="SmallInt NOT NULL")>  _
	Public Property ProgramID() As Short
		Get
			Return Me._ProgramID
		End Get
		Set
			If ((Me._ProgramID = value)  _
						= false) Then
				Me._ProgramID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProgramName", DbType:="NVarChar(27) NOT NULL", CanBeNull:=false)>  _
	Public Property ProgramName() As String
		Get
			Return Me._ProgramName
		End Get
		Set
			If (String.Equals(Me._ProgramName, value) = false) Then
				Me._ProgramName = value
			End If
		End Set
	End Property
End Class

Partial Public Class GetArticlesResult
	
	Private _ArticleID As Integer
	
	Private _ArticleName As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ArticleID", DbType:="Int NOT NULL")>  _
	Public Property ArticleID() As Integer
		Get
			Return Me._ArticleID
		End Get
		Set
			If ((Me._ArticleID = value)  _
						= false) Then
				Me._ArticleID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ArticleName", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property ArticleName() As String
		Get
			Return Me._ArticleName
		End Get
		Set
			If (String.Equals(Me._ArticleName, value) = false) Then
				Me._ArticleName = value
			End If
		End Set
	End Property
End Class

Partial Public Class GetArtHistResult
	
	Private _StartTime As System.Nullable(Of Date)
	
	Private _EndTime As System.Nullable(Of Date)
	
	Private _SysID As Integer
	
	Private _SysShortName As String
	
	Private _SystemMaster As Boolean
	
	Private _MachID As Integer
	
	Private _MachShortName As String
	
	Private _ProdDur As System.Nullable(Of Double)
	
	Private _ArticleName As String
	
	Private _ArticleID As Integer
	
	Private _Counter As System.Nullable(Of Double)
	
	Private _TargetDur1 As System.Nullable(Of Double)
	
	Private _UnitName As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StartTime", DbType:="DateTime")>  _
	Public Property StartTime() As System.Nullable(Of Date)
		Get
			Return Me._StartTime
		End Get
		Set
			If (Me._StartTime.Equals(value) = false) Then
				Me._StartTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EndTime", DbType:="DateTime")>  _
	Public Property EndTime() As System.Nullable(Of Date)
		Get
			Return Me._EndTime
		End Get
		Set
			If (Me._EndTime.Equals(value) = false) Then
				Me._EndTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SysID", DbType:="Int NOT NULL")>  _
	Public Property SysID() As Integer
		Get
			Return Me._SysID
		End Get
		Set
			If ((Me._SysID = value)  _
						= false) Then
				Me._SysID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SysShortName", DbType:="NVarChar(10)")>  _
	Public Property SysShortName() As String
		Get
			Return Me._SysShortName
		End Get
		Set
			If (String.Equals(Me._SysShortName, value) = false) Then
				Me._SysShortName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SystemMaster", DbType:="Bit NOT NULL")>  _
	Public Property SystemMaster() As Boolean
		Get
			Return Me._SystemMaster
		End Get
		Set
			If ((Me._SystemMaster = value)  _
						= false) Then
				Me._SystemMaster = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MachID", DbType:="Int NOT NULL")>  _
	Public Property MachID() As Integer
		Get
			Return Me._MachID
		End Get
		Set
			If ((Me._MachID = value)  _
						= false) Then
				Me._MachID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MachShortName", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property MachShortName() As String
		Get
			Return Me._MachShortName
		End Get
		Set
			If (String.Equals(Me._MachShortName, value) = false) Then
				Me._MachShortName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProdDur", DbType:="Float")>  _
	Public Property ProdDur() As System.Nullable(Of Double)
		Get
			Return Me._ProdDur
		End Get
		Set
			If (Me._ProdDur.Equals(value) = false) Then
				Me._ProdDur = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ArticleName", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property ArticleName() As String
		Get
			Return Me._ArticleName
		End Get
		Set
			If (String.Equals(Me._ArticleName, value) = false) Then
				Me._ArticleName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ArticleID", DbType:="Int NOT NULL")>  _
	Public Property ArticleID() As Integer
		Get
			Return Me._ArticleID
		End Get
		Set
			If ((Me._ArticleID = value)  _
						= false) Then
				Me._ArticleID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Counter", DbType:="Float")>  _
	Public Property Counter() As System.Nullable(Of Double)
		Get
			Return Me._Counter
		End Get
		Set
			If (Me._Counter.Equals(value) = false) Then
				Me._Counter = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TargetDur1", DbType:="Float")>  _
	Public Property TargetDur1() As System.Nullable(Of Double)
		Get
			Return Me._TargetDur1
		End Get
		Set
			If (Me._TargetDur1.Equals(value) = false) Then
				Me._TargetDur1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UnitName", DbType:="NVarChar(10)")>  _
	Public Property UnitName() As String
		Get
			Return Me._UnitName
		End Get
		Set
			If (String.Equals(Me._UnitName, value) = false) Then
				Me._UnitName = value
			End If
		End Set
	End Property
End Class
