<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>FacAttachSqlBackup</AssemblyName>
    <RootNamespace>FacAttachSqlBackup</RootNamespace>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
