// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.ComponentModel;
using System.Configuration;
using System.Diagnostics;

namespace ActiveDev.Data.SqlClient.My
{
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal sealed partial class MySettings : ApplicationSettingsBase
    {
        private static MySettings defaultInstance = (MySettings)Synchronized(new MySettings());

        public static MySettings Default => defaultInstance;

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string AttachDatabaseDialogConnectionString
        {
            get => (string)this["AttachDatabaseDialogConnectionString"];
            set => this["AttachDatabaseDialogConnectionString"] = value;
        }
    }
}
