<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Facesso.EntityModel</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="System.Data.Entity" />
    <Reference Include="System.Security" />
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>

  <ItemGroup>
    <EntityDeploy Include="FacessoModel.edmx" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Facesso.Generic\Facesso.Generic.csproj" />
  </ItemGroup>

</Project>
