//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Configuration;
using System.Runtime.CompilerServices;

namespace ActiveDev.Controls.My
{
    [CompilerGenerated]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal sealed partial class Settings : ApplicationSettingsBase
    {
        private static readonly Settings defaultInstance =
            (Settings)Synchronized(new Settings());

        public static Settings Default
        {
            get { return defaultInstance; }
        }
    }

    [CompilerGenerated]
    internal static class MySettingsProperty
    {
        internal static Settings Settings
        {
            get { return ActiveDev.Controls.My.Settings.Default; }
        }
    }
}
